from . import probe as probe
from _typeshed import Incomplete

class BedTilt:
    printer: Incomplete
    x_adjust: Incomplete
    y_adjust: Incomplete
    z_adjust: Incomplete
    toolhead: Incomplete
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    def get_position(self): ...
    def move(self, newpos, speed) -> None: ...
    def update_adjust(self, x_adjust, y_adjust, z_adjust) -> None: ...

class BedTiltCalibrate:
    printer: Incomplete
    bedtilt: Incomplete
    probe_helper: Incomplete
    gcode: Incomplete
    def __init__(self, config, bedtilt) -> None: ...
    cmd_BED_TILT_CALIBRATE_help: str
    def cmd_BED_TILT_CALIBRATE(self, gcmd) -> None: ...
    def probe_finalize(self, positions) -> None: ...

def load_config(config): ...
