from . import probe as probe
from _typeshed import Incomplete
from collections.abc import Generator
from typing import Any

from klippy import configfile
from klippy.gcode import GCodeCommand, GCodeDispatch
from klippy.toolhead import ToolHead
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from klippy.klippy import Printer

PROFILE_VERSION: int
PROFILE_OPTIONS: Incomplete

class BedMeshError(Exception): ...

def isclose(a, b, rel_tol: float = 1e-09, abs_tol: float = 0.0): ...
def within(coord, min_c, max_c, tol: float = 0.0): ...
def constrain(val, min_val, max_val): ...
def lerp(t, v0, v1): ...
def parse_config_pair(config, option, default, minval=None, maxval=None): ...
def parse_gcmd_pair(gcmd, name, minval=None, maxval=None): ...
def parse_gcmd_coord(gcmd, name): ...

class BedMesh:
    FADE_DISABLE: int
    printer: Printer
    last_position: list[float]
    bmc: Incomplete
    z_mesh: ZMesh | None
    toolhead: ToolHead
    horizontal_move_z: float
    fade_start: float
    fade_end: float
    fade_dist: float
    log_fade_complete: bool
    base_fade_target: float | None
    fade_target: float
    tool_offset: float
    gcode: GCodeDispatch
    splitter: Incomplete
    pmgr: Incomplete
    save_profile: Incomplete
    def __init__(self, config: configfile.ConfigWrapper) -> None: ...
    def handle_connect(self) -> None: ...
    def set_mesh(self, mesh: ZMesh | None) -> None: ...
    def get_z_factor(self, z_pos: float) -> float: ...
    def get_position(self) -> list[float]: ...
    def move(self, newpos: list[float], speed: float) -> None: ...
    def get_status(self, eventtime: float | None = None) -> dict[str, Any]: ...
    status: dict[str, Any]
    def update_status(self) -> None: ...
    def get_mesh(self) -> ZMesh | None: ...
    cmd_BED_MESH_OUTPUT_help: str
    def cmd_BED_MESH_OUTPUT(self, gcmd: GCodeCommand) -> None: ...
    cmd_BED_MESH_MAP_help: str
    def cmd_BED_MESH_MAP(self, gcmd: GCodeCommand) -> None: ...
    cmd_BED_MESH_CLEAR_help: str
    def cmd_BED_MESH_CLEAR(self, gcmd: GCodeCommand) -> None: ...
    cmd_BED_MESH_OFFSET_help: str
    def cmd_BED_MESH_OFFSET(self, gcmd: GCodeCommand) -> None: ...

class ZrefMode:
    DISABLED: int
    IN_MESH: int
    PROBE: int

class BedMeshCalibrate:
    ALGOS: Incomplete
    printer: Incomplete
    orig_config: Incomplete
    radius: Incomplete
    mesh_min: Incomplete
    adaptive_margin: Incomplete
    bedmesh: Incomplete
    mesh_config: Incomplete
    probe_mgr: Incomplete
    gcode: Incomplete
    def __init__(self, config, bedmesh) -> None: ...
    def print_generated_points(self, print_func, truncate: bool = False) -> None: ...
    origin: Incomplete
    mesh_max: Incomplete
    def set_adaptive_mesh(self, gcmd): ...
    def update_config(self, gcmd) -> None: ...
    def dump_calibration(self, gcmd=None): ...
    cmd_BED_MESH_CALIBRATE_help: str
    def cmd_BED_MESH_CALIBRATE(self, gcmd) -> None: ...
    def probe_finalize(self, positions): ...

class ProbeManager:
    printer: Incomplete
    cfg_overshoot: Incomplete
    orig_config: Incomplete
    faulty_regions: Incomplete
    overshoot: Incomplete
    zero_ref_pos: Incomplete
    zref_mode: Incomplete
    base_points: Incomplete
    substitutes: Incomplete
    is_round: Incomplete
    probe_helper: Incomplete
    rapid_scan_helper: Incomplete
    def __init__(self, config, orig_config, finalize_cb) -> None: ...
    def start_probe(self, gcmd) -> None: ...
    def get_zero_ref_pos(self): ...
    def get_zero_ref_mode(self): ...
    def get_substitutes(self): ...
    def generate_points(
        self,
        mesh_config,
        mesh_min,
        mesh_max,
        radius,
        origin,
        probe_method: str = "automatic",
    ) -> None: ...
    def get_base_points(self): ...
    def get_std_path(self): ...
    def iter_rapid_path(self) -> Generator[Incomplete]: ...

MAX_HIT_DIST: float
MM_WIN_SPEED: int

class RapidScanHelper:
    printer: Incomplete
    probe_manager: Incomplete
    speed: Incomplete
    scan_height: Incomplete
    finalize_callback: Incomplete
    def __init__(self, config, probe_mgr, finalize_cb) -> None: ...
    def perform_rapid_scan(self, gcmd) -> None: ...

class MoveSplitter:
    split_delta_z: Incomplete
    move_check_distance: Incomplete
    z_mesh: Incomplete
    fade_offset: float
    gcode: Incomplete
    def __init__(self, config, gcode) -> None: ...
    def initialize(self, mesh, fade_offset) -> None: ...
    prev_pos: Incomplete
    next_pos: Incomplete
    current_pos: Incomplete
    z_factor: Incomplete
    z_offset: Incomplete
    traverse_complete: bool
    distance_checked: float
    total_move_length: Incomplete
    axis_move: Incomplete
    def build_move(self, prev_pos, next_pos, factor) -> None: ...
    def split(self): ...

class ZMesh:
    profile_name: Incomplete
    probed_matrix: Incomplete
    mesh_params: Incomplete
    mesh_offsets: Incomplete
    mesh_x_min: Incomplete
    mesh_x_max: Incomplete
    mesh_y_min: Incomplete
    mesh_y_max: Incomplete
    mesh_x_count: Incomplete
    mesh_y_count: Incomplete
    x_mult: Incomplete
    y_mult: Incomplete
    mesh_x_dist: Incomplete
    mesh_y_dist: Incomplete
    def __init__(self, params, name) -> None: ...
    def get_mesh_matrix(self): ...
    def get_probed_matrix(self): ...
    def get_mesh_params(self): ...
    def get_profile_name(self): ...
    def print_probed_matrix(self, print_func) -> None: ...
    def print_mesh(self, print_func, move_z=None) -> None: ...
    def build_mesh(self, z_matrix) -> None: ...
    def set_zero_reference(self, xpos, ypos) -> None: ...
    def set_mesh_offsets(self, offsets) -> None: ...
    def get_x_coordinate(self, index): ...
    def get_y_coordinate(self, index): ...
    def calc_z(self, x, y): ...
    def get_z_range(self): ...
    def get_z_average(self): ...

class ProfileManager:
    name: Incomplete
    printer: Incomplete
    gcode: Incomplete
    bedmesh: Incomplete
    profiles: Incomplete
    incompatible_profiles: Incomplete
    def __init__(self, config, bedmesh) -> None: ...
    def get_profiles(self): ...
    def save_profile(self, prof_name) -> None: ...
    def load_profile(self, prof_name) -> None: ...
    def remove_profile(self, prof_name) -> None: ...
    cmd_BED_MESH_PROFILE_help: str
    def cmd_BED_MESH_PROFILE(self, gcmd) -> None: ...

def load_config(config: configfile.ConfigWrapper) -> BedMesh: ...
