from _typeshed import Incomplete

class BedScrews:
    printer: Incomplete
    number_of_screws: int
    states: Incomplete
    speed: Incomplete
    lift_speed: Incomplete
    horizontal_move_z: Incomplete
    probe_z: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    state: Incomplete
    current_screw: int
    accepted_screws: int
    def reset(self) -> None: ...
    def move(self, coord, speed) -> None: ...
    def move_to_screw(self, state, screw) -> None: ...
    def unregister_commands(self) -> None: ...
    def get_status(self, eventtime): ...
    cmd_BED_SCREWS_ADJUST_help: str
    def cmd_BED_SCREWS_ADJUST(self, gcmd) -> None: ...
    cmd_ACCEPT_help: str
    def cmd_ACCEPT(self, gcmd) -> None: ...
    cmd_ADJUSTED_help: str
    def cmd_ADJUSTED(self, gcmd) -> None: ...
    cmd_ABORT_help: str
    def cmd_ABORT(self, gcmd) -> None: ...

def load_config(config): ...
