from _typeshed import Incomplete

def resolve_bus_name(mcu, param, bus): ...

class MCU_SPI:
    mcu: Incomplete
    bus: Incomplete
    speed: Incomplete
    oid: Incomplete
    config_fmt_ticks: Incomplete
    config_fmt: Incomplete
    cmd_queue: Incomplete
    spi_send_cmd: Incomplete
    def __init__(
        self, mcu, bus, pin, mode, speed, sw_pins=None, cs_active_high: bool = False
    ) -> None: ...
    def setup_shutdown_msg(self, shutdown_seq) -> None: ...
    def get_oid(self): ...
    def get_mcu(self): ...
    def get_command_queue(self): ...
    spi_transfer_cmd: Incomplete
    def build_config(self) -> None: ...
    def spi_send(self, data, minclock: int = 0, reqclock: int = 0) -> None: ...
    def spi_transfer(self, data, minclock: int = 0, reqclock: int = 0): ...
    def spi_transfer_with_preface(
        self, preface_data, data, minclock: int = 0, reqclock: int = 0
    ): ...

def MCU_SPI_from_config(
    config,
    mode,
    pin_option: str = "cs_pin",
    default_speed: int = 100000,
    share_type=None,
    cs_active_high: bool = False,
): ...

class MCU_I2C:
    mcu: Incomplete
    bus: Incomplete
    i2c_address: Incomplete
    oid: Incomplete
    speed: Incomplete
    async_write_only: Incomplete
    config_fmt_ticks: Incomplete
    config_fmt: Incomplete
    cmd_queue: Incomplete
    i2c_write_cmd: Incomplete
    i2c_transfer_cmd: Incomplete
    def __init__(
        self, mcu, bus, addr, speed, sw_pins=None, async_write_only: bool = False
    ) -> None: ...
    def get_oid(self): ...
    def get_mcu(self): ...
    def get_i2c_address(self): ...
    def get_command_queue(self): ...
    i2c_write_only_cmd: Incomplete
    i2c_read_cmd: Incomplete
    def build_config(self) -> None: ...
    def i2c_write_noack(self, data, minclock: int = 0, reqclock: int = 0) -> None: ...
    def i2c_write(
        self, data, minclock: int = 0, reqclock: int = 0, retry: bool = True
    ) -> None: ...
    def i2c_read(self, write, read_len, retry: bool = True): ...
    def i2c_transfer(
        self,
        write,
        read_len: int = 0,
        minclock: int = 0,
        reqclock: int = 0,
        retry: bool = True,
    ): ...

def MCU_I2C_from_config(
    config,
    default_addr=None,
    default_speed: int = 100000,
    async_write_only: bool = False,
): ...

class MCU_bus_digital_out:
    mcu: Incomplete
    oid: Incomplete
    cmd_queue: Incomplete
    update_pin_cmd: Incomplete
    def __init__(self, mcu, pin_desc, cmd_queue=None, value: int = 0) -> None: ...
    def get_oid(self): ...
    def get_mcu(self): ...
    def get_command_queue(self): ...
    def build_config(self) -> None: ...
    def update_digital_out(
        self, value, minclock: int = 0, reqclock: int = 0
    ) -> None: ...
