from _typeshed import Incomplete

TRINAMIC_DRIVERS: Incomplete

class PhaseCalc:
    printer: Incomplete
    name: Incomplete
    phases: Incomplete
    tmc_module: Incomplete
    phase_history: Incomplete
    is_primary: bool
    def __init__(self, printer, name, phases=None) -> None: ...
    def lookup_tmc(self) -> None: ...
    def convert_phase(self, driver_phase, driver_phases): ...
    last_phase: Incomplete
    last_mcu_position: Incomplete
    def calc_phase(self, stepper, trig_mcu_pos): ...

class EndstopPhase:
    printer: Incomplete
    name: Incomplete
    step_dist: Incomplete
    phases: Incomplete
    phase_calc: Incomplete
    endstop_phase: Incomplete
    endstop_align_zero: Incomplete
    endstop_accuracy: Incomplete
    endstop_phase_accuracy: Incomplete
    def __init__(self, config) -> None: ...
    def align_endstop(self, rail): ...
    def get_homed_offset(self, stepper, trig_mcu_pos): ...
    def handle_home_rails_end(self, homing_state, rails) -> None: ...

class EndstopPhases:
    printer: Incomplete
    tracking: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    def update_stepper(self, stepper, trig_mcu_pos, is_primary) -> None: ...
    def handle_home_rails_end(self, homing_state, rails) -> None: ...
    cmd_ENDSTOP_PHASE_CALIBRATE_help: str
    def cmd_ENDSTOP_PHASE_CALIBRATE(self, gcmd) -> None: ...
    def generate_stats(self, stepper_name, phase_calc): ...
    def report_stats(self) -> None: ...
    def get_status(self, eventtime): ...

def load_config_prefix(config): ...
def load_config(config): ...
