from _typeshed import Incomplete

class ExcludeObject:
    printer: Incomplete
    gcode: Incomplete
    gcode_move: Incomplete
    next_transform: Incomplete
    last_position_extruded: Incomplete
    last_position_excluded: Incomplete
    def __init__(self, config) -> None: ...
    def get_position(self): ...
    def get_status(self, eventtime=None): ...
    last_speed: Incomplete
    def move(self, newpos, speed) -> None: ...
    cmd_EXCLUDE_OBJECT_START_help: str
    current_object: Incomplete
    was_excluded_at_start: Incomplete
    def cmd_EXCLUDE_OBJECT_START(self, gcmd) -> None: ...
    cmd_EXCLUDE_OBJECT_END_help: str
    def cmd_EXCLUDE_OBJECT_END(self, gcmd) -> None: ...
    cmd_EXCLUDE_OBJECT_help: str
    excluded_objects: Incomplete
    def cmd_EXCLUDE_OBJECT(self, gcmd) -> None: ...
    cmd_EXCLUDE_OBJECT_DEFINE_help: str
    def cmd_EXCLUDE_OBJECT_DEFINE(self, gcmd) -> None: ...

def load_config(config): ...
