from _typeshed import Incomplete

class PrinterExtruderStepper:
    printer: Incomplete
    extruder_stepper: Incomplete
    extruder_name: Incomplete
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    def find_past_position(self, print_time): ...
    def get_status(self, eventtime): ...

def load_config_prefix(config): ...
