from _typeshed import Incomplete

class FirmwareRetraction:
    printer: Incomplete
    retract_length: Incomplete
    retract_speed: Incomplete
    unretract_extra_length: Incomplete
    unretract_speed: Incomplete
    unretract_length: Incomplete
    is_retracted: bool
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    cmd_SET_RETRACTION_help: str
    def cmd_SET_RETRACTION(self, gcmd) -> None: ...
    cmd_GET_RETRACTION_help: str
    def cmd_GET_RETRACTION(self, gcmd) -> None: ...
    def cmd_G10(self, gcmd) -> None: ...
    def cmd_G11(self, gcmd) -> None: ...

def load_config(config): ...
