from _typeshed import Incomplete

BUZZ_DISTANCE: float
BUZZ_VELOCITY: Incomplete
BUZZ_RADIANS_DISTANCE: Incomplete
BUZZ_RADIANS_VELOCITY: Incomplete

def calc_move_time(dist, speed, accel): ...

class ForceMove:
    printer: Incomplete
    steppers: Incomplete
    motion_queuing: Incomplete
    trapq: Incomplete
    trapq_append: Incomplete
    stepper_kinematics: Incomplete
    def __init__(self, config) -> None: ...
    def register_stepper(self, config, mcu_stepper) -> None: ...
    def lookup_stepper(self, name): ...
    def manual_move(self, stepper, dist, speed, accel: float = 0.0) -> None: ...
    cmd_STEPPER_BUZZ_help: str
    def cmd_STEPPER_BUZZ(self, gcmd) -> None: ...
    cmd_FORCE_MOVE_help: str
    def cmd_FORCE_MOVE(self, gcmd) -> None: ...
    cmd_SET_KINEMATIC_POSITION_help: str
    def cmd_SET_KINEMATIC_POSITION(self, gcmd) -> None: ...

def load_config(config): ...
