from typing import Any

from klippy import configfile
from klippy.gcode import GCodeCommand, Coord
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from klippy.klippy import Printer

class GCodeMove:
    printer: Printer
    is_printer_ready: bool
    Coord: type[Coord]
    absolute_coord: bool
    base_position: list[float]
    last_position: list[float]
    homing_position: list[float]
    axis_map: dict[str, int]
    speed: float
    speed_factor: float
    extrude_factor: float
    saved_states: dict[str, dict[str, Any]]
    move_transform: Any | None
    position_with_transform: Any
    def __init__(self, config: configfile.ConfigWrapper) -> None: ...
    move_with_transform: Any
    def set_move_transform(self, transform: Any, force: bool = False) -> None: ...
    def get_status(self, eventtime: float | None = None) -> dict[str, Any]: ...
    def reset_last_position(self) -> None: ...
    def cmd_G1(self, gcmd: GCodeCommand) -> None: ...
    def cmd_G20(self, gcmd: GCodeCommand) -> None: ...
    def cmd_G21(self, gcmd: GCodeCommand) -> None: ...
    absolute_extrude: bool
    def cmd_M82(self, gcmd: GCodeCommand) -> None: ...
    def cmd_M83(self, gcmd: GCodeCommand) -> None: ...
    def cmd_G90(self, gcmd: GCodeCommand) -> None: ...
    def cmd_G91(self, gcmd: GCodeCommand) -> None: ...
    def cmd_G92(self, gcmd: GCodeCommand) -> None: ...
    def cmd_M114(self, gcmd: GCodeCommand) -> None: ...
    def cmd_M220(self, gcmd: GCodeCommand) -> None: ...
    def cmd_M221(self, gcmd: GCodeCommand) -> None: ...
    cmd_SET_GCODE_OFFSET_help: str
    def cmd_SET_GCODE_OFFSET(self, gcmd: GCodeCommand) -> None: ...
    cmd_SAVE_GCODE_STATE_help: str
    def cmd_SAVE_GCODE_STATE(self, gcmd: GCodeCommand) -> None: ...
    cmd_RESTORE_GCODE_STATE_help: str
    def cmd_RESTORE_GCODE_STATE(self, gcmd: GCodeCommand) -> None: ...
    cmd_GET_POSITION_help: str
    def cmd_GET_POSITION(self, gcmd: GCodeCommand) -> None: ...

def load_config(config: configfile.ConfigWrapper) -> GCodeMove: ...
