from _typeshed import Incomplete

DEFAULT_IDLE_GCODE: str
PIN_MIN_TIME: float
READY_TIMEOUT: float

class IdleTimeout:
    printer: Incomplete
    reactor: Incomplete
    gcode: Incomplete
    toolhead: Incomplete
    idle_timeout: Incomplete
    idle_gcode: Incomplete
    state: str
    last_print_start_systime: float
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    timeout_timer: Incomplete
    def handle_ready(self) -> None: ...
    def transition_idle_state(self, eventtime): ...
    def check_idle_timeout(self, eventtime): ...
    def timeout_handler(self, eventtime): ...
    def handle_sync_print_time(self, curtime, print_time, est_print_time) -> None: ...
    cmd_SET_IDLE_TIMEOUT_help: str
    def cmd_SET_IDLE_TIMEOUT(self, gcmd) -> None: ...

def load_config(config): ...
