from . import bus as bus
from _typeshed import Incomplete

LM75_CHIP_ADDR: int
LM75_I2C_SPEED: int
LM75_REGS: Incomplete
LM75_REPORT_TIME: float
LM75_MIN_REPORT_TIME: float

class LM75:
    printer: Incomplete
    name: Incomplete
    reactor: Incomplete
    i2c: Incomplete
    mcu: Incomplete
    report_time: Incomplete
    temp: float
    sample_timer: Incomplete
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    min_temp: Incomplete
    max_temp: Incomplete
    def setup_minmax(self, min_temp, max_temp) -> None: ...
    def setup_callback(self, cb) -> None: ...
    def get_report_time_delta(self): ...
    def degrees_from_sample(self, x): ...
    def read_register(self, reg_name, read_len): ...
    def write_register(self, reg_name, data) -> None: ...
    def get_status(self, eventtime): ...

def load_config(config) -> None: ...
