from . import (
    ads1220 as ads1220,
    ads131m0x as ads131m0x,
    hx71x as hx71x,
    load_cell as load_cell,
    manual_probe as manual_probe,
    probe as probe,
    trigger_analog as trigger_analog,
)
from _typeshed import Incomplete

np: Incomplete
FRAC_GRAMS_CONV: float

class TapAnalysis:
    time: Incomplete
    force: Incomplete
    def __init__(self, samples) -> None: ...
    def to_dict(self): ...

class ParamHelper:
    name: Incomplete
    value: Incomplete
    minval: Incomplete
    maxval: Incomplete
    above: Incomplete
    below: Incomplete
    max_len: Incomplete
    def __init__(
        self,
        config,
        name,
        type_name,
        default=None,
        minval=None,
        maxval=None,
        above=None,
        below=None,
        max_len=None,
    ) -> None: ...
    def get(
        self, gcmd=None, minval=None, maxval=None, above=None, below=None, config=None
    ): ...

def intParamHelper(config, name, default=None, minval=None, maxval=None): ...
def floatParamHelper(
    config, name, default=None, minval=None, maxval=None, above=None, below=None
): ...
def floatListParamHelper(
    config, name, default=None, above=None, below=None, max_len=None
): ...

class ContinuousTareFilter:
    sps: Incomplete
    drift: Incomplete
    drift_delay: Incomplete
    buzz: Incomplete
    buzz_delay: Incomplete
    notches: Incomplete
    notch_quality: Incomplete
    def __init__(
        self,
        sps=None,
        drift=None,
        drift_delay=None,
        buzz=None,
        buzz_delay=None,
        notches=None,
        notch_quality=None,
    ) -> None: ...
    def __eq__(self, other): ...
    def design_filter(self, error_func): ...

class ContinuousTareFilterHelper:
    def __init__(self, config, sensor, sos_filter) -> None: ...
    def update_from_command(self, gcmd, cq=None) -> None: ...

def check_sensor_errors(results, printer): ...

class LoadCellProbeConfigHelper:
    def __init__(self, config, load_cell_inst) -> None: ...
    def get_tare_samples(self, gcmd=None): ...
    def get_trigger_force_grams(self, gcmd=None): ...
    def get_safety_limit_grams(self, gcmd=None): ...
    def get_safety_range(self, gcmd=None): ...
    def get_grams_per_count(self): ...

class LoadCellProbingMove:
    def __init__(
        self,
        config,
        load_cell_inst,
        mcu_trigger_analog,
        param_helper,
        continuous_tare_filter_helper,
        config_helper,
    ) -> None: ...
    def probing_move(self, gcmd): ...
    def probing_test(self, gcmd, timeout): ...
    def get_status(self, eventtime): ...

class TappingMove:
    def __init__(self, config, load_cell_probing_move, config_helper) -> None: ...
    def run_tap(self, gcmd): ...
    def get_status(self, eventtime): ...

class TapSession:
    def __init__(
        self, config, tapping_move, probe_offsets, probe_params_helper
    ) -> None: ...
    def start_probe_session(self, gcmd): ...
    def end_probe_session(self) -> None: ...
    def run_probe(self, gcmd) -> None: ...
    def pull_probed_results(self): ...

class LoadCellProbeCommands:
    def __init__(self, config, load_cell_probing_move) -> None: ...
    cmd_LOAD_CELL_TEST_TAP_help: str
    def cmd_LOAD_CELL_TEST_TAP(self, gcmd) -> None: ...

class LoadCellPrinterProbe:
    def __init__(self, config) -> None: ...
    def get_probe_params(self, gcmd=None): ...
    def get_offsets(self, gcmd=None): ...
    def start_probe_session(self, gcmd): ...
    def get_status(self, eventtime): ...

def load_config(config): ...
