from _typeshed import Incomplete
from typing import NamedTuple

class ProbeResult(NamedTuple):
    bed_x: Incomplete
    bed_y: Incomplete
    bed_z: Incomplete
    test_x: Incomplete
    test_y: Incomplete
    test_z: Incomplete

def create_probe_result(test_pos, offsets=(0.0, 0.0, 0.0)): ...
def lookup_z_endstop_config(config): ...

class ManualProbe:
    printer: Incomplete
    gcode: Incomplete
    gcode_move: Incomplete
    z_position_endstop: Incomplete
    z_endstop_config_name: Incomplete
    a_position_endstop: Incomplete
    b_position_endstop: Incomplete
    c_position_endstop: Incomplete
    def __init__(self, config) -> None: ...
    def manual_probe_finalize(self, mpresult) -> None: ...
    status: Incomplete
    def reset_status(self) -> None: ...
    def get_status(self, eventtime): ...
    cmd_MANUAL_PROBE_help: str
    def cmd_MANUAL_PROBE(self, gcmd) -> None: ...
    def z_endstop_finalize(self, mpresult) -> None: ...
    cmd_Z_ENDSTOP_CALIBRATE_help: str
    def cmd_Z_ENDSTOP_CALIBRATE(self, gcmd) -> None: ...
    def cmd_Z_OFFSET_APPLY_ENDSTOP(self, gcmd) -> None: ...
    def cmd_Z_OFFSET_APPLY_DELTA_ENDSTOPS(self, gcmd) -> None: ...
    cmd_Z_OFFSET_APPLY_ENDSTOP_help: str

def verify_no_manual_probe(printer) -> None: ...

Z_BOB_MINIMUM: float
BISECT_MAX: float

class ManualProbeHelper:
    printer: Incomplete
    finalize_callback: Incomplete
    gcode: Incomplete
    toolhead: Incomplete
    manual_probe: Incomplete
    speed: Incomplete
    past_positions: Incomplete
    last_toolhead_pos: Incomplete
    start_position: Incomplete
    def __init__(self, printer, gcmd, finalize_callback) -> None: ...
    last_kinematics_pos: Incomplete
    def get_kinematics_pos(self): ...
    def move_z(self, z_pos) -> None: ...
    def report_z_status(self, warn_no_change: bool = False, prev_pos=None) -> None: ...
    cmd_ACCEPT_help: str
    def cmd_ACCEPT(self, gcmd) -> None: ...
    cmd_ABORT_help: str
    def cmd_ABORT(self, gcmd) -> None: ...
    cmd_TESTZ_help: str
    def cmd_TESTZ(self, gcmd) -> None: ...
    def finalize(self, success) -> None: ...

def load_config(config): ...
