from _typeshed import Incomplete

class PrinterMultiPin:
    printer: Incomplete
    pin_type: Incomplete
    pin_list: Incomplete
    mcu_pins: Incomplete
    def __init__(self, config) -> None: ...
    def setup_pin(self, pin_type, pin_params): ...
    def get_mcu(self): ...
    def setup_max_duration(self, max_duration) -> None: ...
    def setup_start_value(self, start_value, shutdown_value) -> None: ...
    def setup_cycle_time(self, cycle_time, hardware_pwm: bool = False) -> None: ...
    def set_digital(self, print_time, value) -> None: ...
    def next_aligned_print_time(self, print_time, allow_early: float = 0.0): ...
    def set_pwm(self, print_time, value) -> None: ...

def load_config_prefix(config): ...
