from _typeshed import Incomplete

COMMAND_HEARTBEAT: str
COMMAND_CUT: str
COMMAND_CLEAR: Incomplete
COMMAND_FILENAME: str
COMMAND_FILENAMES_DONE: str
COMMAND_FIRMWARE: str
COMMAND_PING: str
COMMAND_SMART_LOAD_STOP: str
HEARTBEAT_SEND: float
HEARTBEAT_TIMEOUT: Incomplete
SETUP_TIMEOUT: int
SERIAL_TIMER: float
AUTOLOAD_TIMER: float
INFO_NOT_CONNECTED: str

class Palette2:
    printer: Incomplete
    reactor: Incomplete
    virtual_sdcard: Incomplete
    pause_resume: Incomplete
    gcode_move: Incomplete
    gcode: Incomplete
    serial: Incomplete
    serial_port: Incomplete
    baud: Incomplete
    feedrate_splice: Incomplete
    feedrate_normal: Incomplete
    auto_load_speed: Incomplete
    auto_cancel_variation: Incomplete
    omega_header: Incomplete
    read_timer: Incomplete
    read_buffer: str
    read_queue: Incomplete
    write_timer: Incomplete
    write_queue: Incomplete
    heartbeat_timer: Incomplete
    heartbeat: Incomplete
    signal_disconnect: bool
    is_printing: bool
    smart_load_timer: Incomplete
    def __init__(self, config) -> None: ...
    cmd_Connect_Help: str
    def cmd_Connect(self, gcmd) -> None: ...
    cmd_Disconnect_Help: str
    def cmd_Disconnect(self, gcmd=None) -> None: ...
    cmd_Clear_Help: str
    def cmd_Clear(self, gcmd) -> None: ...
    cmd_Cut_Help: str
    def cmd_Cut(self, gcmd) -> None: ...
    cmd_Smart_Load_Help: str
    def cmd_Smart_Load(self, gcmd) -> None: ...
    def cmd_OmegaDefault(self, gcmd) -> None: ...
    cmd_O1_help: str
    def cmd_O1(self, gcmd) -> None: ...
    cmd_O9_help: str
    def cmd_O9(self, gcmd) -> None: ...
    def cmd_O21(self, gcmd) -> None: ...
    def cmd_O22(self, gcmd) -> None: ...
    def cmd_O23(self, gcmd) -> None: ...
    def cmd_O24(self, gcmd) -> None: ...
    omega_drives: Incomplete
    def cmd_O25(self, gcmd) -> None: ...
    def cmd_O26(self, gcmd) -> None: ...
    def cmd_O27(self, gcmd) -> None: ...
    def cmd_O28(self, gcmd) -> None: ...
    def cmd_O29(self, gcmd) -> None: ...
    def cmd_O30(self, gcmd) -> None: ...
    omega_current_ping: Incomplete
    def cmd_O31(self, gcmd) -> None: ...
    def cmd_O32(self, gcmd) -> None: ...
    omega_header_counter: Incomplete
    omega_splices_counter: Incomplete
    omega_algorithms_counter: Incomplete
    def p2cmd_O20(self, params) -> None: ...
    def p2cmd_O34(self, params) -> None: ...
    def p2cmd_O40(self, params) -> None: ...
    files: Incomplete
    def p2cmd_O50(self, params) -> None: ...
    def p2cmd_O53(self, params) -> None: ...
    def p2cmd_O88(self, params) -> None: ...
    is_loading: bool
    remaining_load_length: Incomplete
    is_splicing: bool
    def p2cmd_O97(self, params) -> None: ...
    is_setup_complete: bool
    def p2cmd_O100(self, params) -> None: ...
    def p2cmd_O102(self, params) -> None: ...
    def p2cmd(self, line) -> None: ...
    def get_status(self, eventtime=None): ...

def load_config(config): ...
