from _typeshed import Incomplete

class PauseResume:
    printer: Incomplete
    gcode: Incomplete
    recover_velocity: Incomplete
    v_sd: Incomplete
    is_paused: bool
    sd_paused: bool
    pause_command_sent: bool
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    def get_status(self, eventtime): ...
    def is_sd_active(self): ...
    def send_pause_command(self) -> None: ...
    cmd_PAUSE_help: str
    def cmd_PAUSE(self, gcmd) -> None: ...
    def send_resume_command(self) -> None: ...
    cmd_RESUME_help: str
    def cmd_RESUME(self, gcmd) -> None: ...
    cmd_CLEAR_PAUSE_help: str
    def cmd_CLEAR_PAUSE(self, gcmd) -> None: ...
    cmd_CANCEL_PRINT_help: str
    def cmd_CANCEL_PRINT(self, gcmd) -> None: ...

def load_config(config): ...
