from . import heaters as heaters
from _typeshed import Incomplete

class PIDCalibrate:
    printer: Incomplete
    def __init__(self, config) -> None: ...
    cmd_PID_CALIBRATE_help: str
    def cmd_PID_CALIBRATE(self, gcmd) -> None: ...

TUNE_PID_DELTA: float

class ControlAutoTune:
    heater: Incomplete
    heater_max_power: Incomplete
    calibrate_temp: Incomplete
    heating: bool
    peak: float
    peak_time: float
    peaks: Incomplete
    last_pwm: float
    pwm_samples: Incomplete
    temp_samples: Incomplete
    def __init__(self, heater, target) -> None: ...
    def set_pwm(self, read_time, value) -> None: ...
    def temperature_update(self, read_time, temp, target_temp) -> None: ...
    def check_busy(self, eventtime, smoothed_temp, target_temp): ...
    def check_peaks(self) -> None: ...
    def calc_pid(self, pos): ...
    def calc_final_pid(self): ...
    def write_file(self, filename) -> None: ...

def load_config(config): ...
