from . import probe as probe, z_tilt as z_tilt
from _typeshed import Incomplete

class QuadGantryLevel:
    printer: Incomplete
    retry_helper: Incomplete
    max_adjust: Incomplete
    horizontal_move_z: Incomplete
    probe_helper: Incomplete
    z_status: Incomplete
    z_helper: Incomplete
    gantry_corners: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    cmd_QUAD_GANTRY_LEVEL_help: str
    def cmd_QUAD_GANTRY_LEVEL(self, gcmd) -> None: ...
    def probe_finalize(self, positions): ...
    def linefit(self, p1, p2): ...
    def plot(self, f, x): ...
    def get_status(self, eventtime): ...

def load_config(config): ...
