from _typeshed import Incomplete

class QueryADC:
    printer: Incomplete
    adc: Incomplete
    def __init__(self, config) -> None: ...
    def register_adc(self, name, mcu_adc) -> None: ...
    cmd_QUERY_ADC_help: str
    def cmd_QUERY_ADC(self, gcmd) -> None: ...

def load_config(config): ...
