from _typeshed import Incomplete

class SDCardLoop:
    sdcard: Incomplete
    gcode: Incomplete
    loop_stack: Incomplete
    def __init__(self, config) -> None: ...
    cmd_SDCARD_LOOP_BEGIN_help: str
    def cmd_SDCARD_LOOP_BEGIN(self, gcmd) -> None: ...
    cmd_SDCARD_LOOP_END_help: str
    def cmd_SDCARD_LOOP_END(self, gcmd) -> None: ...
    cmd_SDCARD_LOOP_DESIST_help: str
    def cmd_SDCARD_LOOP_DESIST(self, gcmd) -> None: ...
    def loop_begin(self, count): ...
    def loop_end(self): ...
    def loop_desist(self): ...

def load_config(config): ...
