from . import probe as probe
from _typeshed import Incomplete

BITS_PER_SECOND: float

class ControlPinHelper:
    def __init__(self, pin_params) -> None: ...
    def write_bits(self, start_time, bit_stream): ...

class SmartEffectorProbe:
    printer: Incomplete
    gcode: Incomplete
    probe_accel: Incomplete
    recovery_time: Incomplete
    probe_wrapper: Incomplete
    query_endstop: Incomplete
    probe_session: Incomplete
    control_pin: Incomplete
    def __init__(self, config, probe_offsets, param_helper) -> None: ...
    def start_probe_session(self, gcmd): ...
    def run_probe(self, gcmd) -> None: ...
    def pull_probed_results(self): ...
    def end_probe_session(self) -> None: ...
    cmd_SET_SMART_EFFECTOR_help: str
    def cmd_SET_SMART_EFFECTOR(self, gcmd) -> None: ...
    cmd_RESET_SMART_EFFECTOR_help: str
    def cmd_RESET_SMART_EFFECTOR(self, gcmd) -> None: ...

class PrinterSmartEffector:
    printer: Incomplete
    probe_offsets: Incomplete
    param_helper: Incomplete
    mcu_probe: Incomplete
    probe_session: Incomplete
    cmd_helper: Incomplete
    def __init__(self, config) -> None: ...
    def get_probe_params(self, gcmd=None): ...
    def get_offsets(self, gcmd=None): ...
    def get_status(self, eventtime): ...
    def start_probe_session(self, gcmd): ...

def load_config(config): ...
