from . import bus as bus
from _typeshed import Incomplete

REG_RESET: int
REG_CLOCK: int
REG_MISC: int
REG_DIR: int
REG_DATA: int
REG_PULLUP: int
REG_PULLDOWN: int
REG_INPUT_DISABLE: int
REG_ANALOG_DRIVER_ENABLE: int
REG_I_ON: Incomplete

class SX1509:
    reg_dict: Incomplete
    reg_i_on_dict: Incomplete
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    def setup_pin(self, pin_type, pin_params): ...
    def get_mcu(self): ...
    def get_oid(self): ...
    def clear_bits_in_register(self, reg, bitmask) -> None: ...
    def set_bits_in_register(self, reg, bitmask) -> None: ...
    def set_register(self, reg, value) -> None: ...
    def send_register(self, reg, print_time) -> None: ...

class SX1509_digital_out:
    def __init__(self, sx1509, pin_params) -> None: ...
    def get_mcu(self): ...
    def setup_max_duration(self, max_duration) -> None: ...
    def setup_start_value(self, start_value, shutdown_value) -> None: ...
    def set_digital(self, print_time, value) -> None: ...
    def set_pwm(self, print_time, value, cycle_time=None) -> None: ...

class SX1509_pwm:
    def __init__(self, sx1509, pin_params) -> None: ...
    def get_mcu(self): ...
    def setup_max_duration(self, max_duration) -> None: ...
    def setup_cycle_time(self, cycle_time, hardware_pwm: bool = False) -> None: ...
    def setup_start_value(self, start_value, shutdown_value) -> None: ...
    def next_aligned_print_time(self, print_time, allow_early: float = 0.0): ...
    def set_pwm(self, print_time, value) -> None: ...

def load_config_prefix(config): ...
