from _typeshed import Incomplete

REPORT_TIME: float

class PrinterSensorCombined:
    printer: Incomplete
    reactor: Incomplete
    name: Incomplete
    sensor_names: Incomplete
    max_deviation: Incomplete
    sensor: Incomplete
    sensors: Incomplete
    apply_mode: Incomplete
    last_temp: float
    humidity: Incomplete
    temperature_update_timer: Incomplete
    def __init__(self, config) -> None: ...
    min_temp: Incomplete
    max_temp: Incomplete
    def setup_minmax(self, min_temp, max_temp) -> None: ...
    temperature_callback: Incomplete
    def setup_callback(self, temperature_callback) -> None: ...
    def get_report_time_delta(self): ...
    def update_temp(self, eventtime) -> None: ...
    def get_temp(self, eventtime): ...
    pressure: Incomplete
    gas: Incomplete
    def update_additional(self, eventtime) -> None: ...
    def get_status(self, eventtime): ...

def mean(values): ...
def load_config(config) -> None: ...
