from . import bulk_sensor as bulk_sensor
from _typeshed import Incomplete

def ffs(mask): ...

class FieldHelper:
    all_fields: Incomplete
    signed_fields: Incomplete
    field_formatters: Incomplete
    registers: Incomplete
    field_to_register: Incomplete
    def __init__(
        self, all_fields, signed_fields=[], field_formatters={}, registers=None
    ) -> None: ...
    def lookup_register(self, field_name, default=None): ...
    def get_field(self, field_name, reg_value=None, reg_name=None): ...
    def set_field(self, field_name, field_value, reg_value=None, reg_name=None): ...
    def set_config_field(self, config, field_name, default): ...
    def pretty_format(self, reg_name, reg_value): ...
    def get_reg_fields(self, reg_name, reg_value): ...

class TMCErrorCheck:
    printer: Incomplete
    stepper_name: Incomplete
    mcu_tmc: Incomplete
    fields: Incomplete
    check_timer: Incomplete
    last_drv_status: Incomplete
    gstat_reg_info: Incomplete
    clear_gstat: bool
    irun_field: str
    drv_status_reg_info: Incomplete
    adc_temp: Incomplete
    adc_temp_reg: Incomplete
    def __init__(self, config, mcu_tmc) -> None: ...
    def stop_checks(self) -> None: ...
    def start_checks(self): ...
    last_drv_fields: Incomplete
    def get_status(self, eventtime=None): ...

class TMCStallguardDump:
    printer: Incomplete
    stepper_name: Incomplete
    mcu_tmc: Incomplete
    mcu: Incomplete
    fields: Incomplete
    sg2_supp: bool
    sg4_reg_name: Incomplete
    optimized_spi: bool
    samples: Incomplete
    query_timer: Incomplete
    error: Incomplete
    batch_bulk: Incomplete
    def __init__(self, config, mcu_tmc) -> None: ...

class TMCCommandHelper:
    printer: Incomplete
    stepper_name: Incomplete
    name: Incomplete
    mcu_tmc: Incomplete
    current_helper: Incomplete
    fields: Incomplete
    stepper: Incomplete
    mcu_phase_offset: Incomplete
    toff: Incomplete
    stepper_enable: Incomplete
    enable_mutex: Incomplete
    read_registers: Incomplete
    echeck_helper: Incomplete
    record_helper: Incomplete
    def __init__(self, config, mcu_tmc, current_helper) -> None: ...
    cmd_INIT_TMC_help: str
    def cmd_INIT_TMC(self, gcmd) -> None: ...
    cmd_SET_TMC_FIELD_help: str
    def cmd_SET_TMC_FIELD(self, gcmd) -> None: ...
    cmd_SET_TMC_CURRENT_help: str
    def cmd_SET_TMC_CURRENT(self, gcmd) -> None: ...
    def get_phase_offset(self): ...
    def get_status(self, eventtime=None): ...
    read_translate: Incomplete
    def setup_register_dump(self, read_registers, read_translate=None) -> None: ...
    cmd_DUMP_TMC_help: str
    def cmd_DUMP_TMC(self, gcmd) -> None: ...

class TMCVirtualPinHelper:
    printer: Incomplete
    mcu_tmc: Incomplete
    fields: Incomplete
    diag_pin: Incomplete
    diag_pin_field: str
    mcu_endstop: Incomplete
    def __init__(self, config, mcu_tmc) -> None: ...
    def setup_pin(self, pin_type, pin_params): ...
    def handle_homing_move_begin(self, hmove) -> None: ...
    def handle_homing_move_end(self, hmove) -> None: ...

def TMCWaveTableHelper(config, mcu_tmc) -> None: ...
def TMCMicrostepHelper(config, mcu_tmc) -> None: ...
def TMCtstepHelper(mcu_tmc, velocity, pstepper=None, config=None): ...
def TMCStealthchopHelper(config, mcu_tmc) -> None: ...
def TMCVcoolthrsHelper(config, mcu_tmc) -> None: ...
def TMCVhighHelper(config, mcu_tmc) -> None: ...
