from _typeshed import Incomplete

class MCU_analog_mux:
    mcu: Incomplete
    cmd_queue: Incomplete
    oids: Incomplete
    pins: Incomplete
    pin_values: Incomplete
    update_pin_cmd: Incomplete
    def __init__(self, mcu, cmd_queue, select_pins_desc) -> None: ...
    def build_config(self) -> None: ...
    def get_instance_id(self, select_pins_desc): ...
    def activate(self, instance_id) -> None: ...

class PrinterTMCUartMutexes:
    mcu_to_mutex: Incomplete
    def __init__(self) -> None: ...

def lookup_tmc_uart_mutex(mcu): ...

TMC_BAUD_RATE: int
TMC_BAUD_RATE_AVR: int

class MCU_TMC_uart_bitbang:
    mcu: Incomplete
    mutex: Incomplete
    pullup: Incomplete
    rx_pin: Incomplete
    tx_pin: Incomplete
    oid: Incomplete
    cmd_queue: Incomplete
    analog_mux: Incomplete
    instances: Incomplete
    tmcuart_send_cmd: Incomplete
    def __init__(self, rx_pin_params, tx_pin_params, select_pins_desc) -> None: ...
    def build_config(self) -> None: ...
    def register_instance(
        self, rx_pin_params, tx_pin_params, select_pins_desc, addr
    ): ...
    def reg_read(self, instance_id, addr, reg): ...
    def reg_write(self, instance_id, addr, reg, val, print_time=None) -> None: ...
    def get_mcu(self): ...

def lookup_tmc_uart_bitbang(config, max_addr): ...

class MCU_TMC_uart:
    printer: Incomplete
    name: Incomplete
    name_to_reg: Incomplete
    fields: Incomplete
    ifcnt: Incomplete
    mutex: Incomplete
    tmc_frequency: Incomplete
    def __init__(
        self, config, name_to_reg, fields, max_addr, tmc_frequency
    ) -> None: ...
    def get_fields(self): ...
    def get_register_raw(self, reg_name): ...
    def get_register(self, reg_name): ...
    def set_register(self, reg_name, val, print_time=None) -> None: ...
    def get_tmc_frequency(self): ...
    def get_mcu(self): ...
