from _typeshed import Incomplete

MAX_INT32: Incomplete
MIN_INT32: Incomplete

def assert_is_int32(value, frac_bits): ...
def to_fixed_32(value, frac_bits: int = 0): ...
def calc_frac_bits(values): ...

GeneratedSOS: Incomplete

def pre_gen_filt(btype, sps, freq, order) -> None: ...

class DigitalFilter:
    filter_sections: Incomplete
    initial_state: Incomplete
    sample_frequency: Incomplete
    cfg_error: Incomplete
    def __init__(self, sps, cfg_error) -> None: ...
    def get_scipy_signal(self): ...
    def add_highpass(self, highpass, highpass_order) -> None: ...
    def add_lowpass(self, lowpass, lowpass_order) -> None: ...
    def add_notch(self, notch_freq, notch_quality) -> None: ...
    def add_derivative(self) -> None: ...
    def setup_initial_state(self) -> None: ...
    def get_filter_sections(self): ...
    def get_initial_state(self): ...
    def get_size(self): ...

class MCU_SosFilter:
    def __init__(self, mcu, cmd_queue, max_sections) -> None: ...
    def get_oid(self): ...
    def set_start_state(self, start_value) -> None: ...
    def set_offset_scale(
        self, offset: int = 0, scale: float = 1.0, auto_offset: bool = False
    ) -> None: ...
    def set_filter_design(self, design) -> None: ...
    def reset_filter(self) -> None: ...

class MCU_trigger_analog:
    MONITOR_MAX: int
    REASON_TRIGGER_ANALOG: Incomplete
    def __init__(self, sensor_inst) -> None: ...
    def setup_sos_filter(self, sos_filter) -> None: ...
    def get_oid(self): ...
    def get_mcu(self): ...
    def get_sos_filter(self): ...
    def get_dispatch(self): ...
    def get_last_trigger_time(self): ...
    def set_trigger(self, trigger_type, trigger_value) -> None: ...
    def set_raw_range(self, raw_min, raw_max) -> None: ...
    def get_steppers(self): ...
    def home_start(
        self, print_time, sample_time, sample_count, rest_time, triggered: bool = True
    ): ...
    def home_wait(self, home_end_time): ...
