from _typeshed import Incomplete

VALID_GCODE_EXTS: Incomplete
DEFAULT_ERROR_GCODE: str

class VirtualSD:
    printer: Incomplete
    sdcard_dirname: Incomplete
    current_file: Incomplete
    file_position: int
    print_stats: Incomplete
    reactor: Incomplete
    must_pause_work: bool
    next_file_position: int
    work_timer: Incomplete
    on_error_gcode: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    def stats(self, eventtime): ...
    def get_file_list(self, check_subdirs: bool = False): ...
    def get_status(self, eventtime): ...
    def file_path(self): ...
    def progress(self): ...
    def is_active(self): ...
    def do_pause(self) -> None: ...
    def do_resume(self) -> None: ...
    def do_cancel(self) -> None: ...
    def cmd_error(self, gcmd) -> None: ...
    cmd_SDCARD_RESET_FILE_help: str
    def cmd_SDCARD_RESET_FILE(self, gcmd) -> None: ...
    cmd_SDCARD_PRINT_FILE_help: str
    def cmd_SDCARD_PRINT_FILE(self, gcmd) -> None: ...
    def cmd_M20(self, gcmd) -> None: ...
    def cmd_M21(self, gcmd) -> None: ...
    def cmd_M23(self, gcmd) -> None: ...
    def cmd_M24(self, gcmd) -> None: ...
    def cmd_M25(self, gcmd) -> None: ...
    def cmd_M26(self, gcmd) -> None: ...
    def cmd_M27(self, gcmd) -> None: ...
    def get_file_position(self): ...
    def set_file_position(self, pos) -> None: ...
    def is_cmd_from_sd(self): ...
    cmd_from_sd: bool
    def work_handler(self, eventtime): ...

def load_config(config): ...
