from typing import Any

class FFI:
    def cdef(self, source: str) -> None: ...
    def dlopen(self, path: str) -> Any: ...
    def callback(self, signature: str, callback: Any) -> Any: ...
    def string(self, cdata: Any) -> str: ...
    def gc(self, cdata: Any, destructor: Any) -> Any: ...
