from _typeshed import Incomplete

SAMPLE_TIME: float
SAMPLE_COUNT: int
REPORT_TIME: float
RANGE_CHECK_COUNT: int

class PrinterADCtoTemperature:
    adc_convert: Incomplete
    mcu_adc: Incomplete
    diag_helper: Incomplete
    def __init__(self, config, adc_convert) -> None: ...
    temperature_callback: Incomplete
    def setup_callback(self, temperature_callback) -> None: ...
    def get_report_time_delta(self): ...
    def adc_callback(self, samples) -> None: ...
    def setup_minmax(self, min_temp, max_temp) -> None: ...

class HelperTemperatureDiagnostics:
    printer: Incomplete
    name: Incomplete
    mcu_adc: Incomplete
    calc_temp_cb: Incomplete
    min_temp: Incomplete
    def __init__(self, config, mcu_adc, calc_temp_cb) -> None: ...
    def setup_diag_minmax(self, min_temp, max_temp, min_adc, max_adc) -> None: ...

class LinearInterpolate:
    keys: Incomplete
    slopes: Incomplete
    def __init__(self, samples) -> None: ...
    def interpolate(self, key): ...
    def reverse_interpolate(self, value): ...

class LinearVoltage:
    calc_temp: Incomplete
    calc_adc: Incomplete
    def __init__(self, config, params) -> None: ...

class CustomLinearVoltage:
    name: Incomplete
    params: Incomplete
    def __init__(self, config) -> None: ...
    def create(self, config): ...

class LinearResistance:
    pullup: Incomplete
    li: Incomplete
    def __init__(self, config, samples) -> None: ...
    def calc_temp(self, adc): ...
    def calc_adc(self, temp): ...

class CustomLinearResistance:
    name: Incomplete
    samples: Incomplete
    def __init__(self, config) -> None: ...
    def create(self, config): ...

AD595: Incomplete
AD597: Incomplete
AD8494: Incomplete
AD8495: Incomplete
AD8496: Incomplete
AD8497: Incomplete

def calc_pt100(base: float = 100.0): ...
def calc_ina826_pt100(): ...

DefaultVoltageSensors: Incomplete
DefaultResistanceSensors: Incomplete

def load_config(config): ...
def load_config_prefix(config) -> None: ...
