from _typeshed import Incomplete

class PrinterCANBusStats:
    printer: Incomplete
    reactor: Incomplete
    name: Incomplete
    mcu: Incomplete
    get_canbus_status_cmd: Incomplete
    status: Incomplete
    def __init__(self, config) -> None: ...
    def handle_shutdown(self) -> None: ...
    def handle_connect(self) -> None: ...
    def handle_usb_canbus_state(self, params) -> None: ...
    def query_event(self, eventtime): ...
    def stats(self, eventtime): ...
    def get_status(self, eventtime): ...

def load_config_prefix(config): ...
