from _typeshed import Incomplete

NODEID_FIRST: int

class PrinterCANBus:
    printer: Incomplete
    ids: Incomplete
    def __init__(self, config) -> None: ...
    def add_uuid(self, config, canbus_uuid, canbus_iface): ...
    def get_nodeid(self, canbus_uuid): ...

def load_config(config): ...
