from . import bus as bus
from _typeshed import Incomplete

class dac084S085:
    spi: Incomplete
    def __init__(self, config) -> None: ...
    def set_register(self, chan, value) -> None: ...

def load_config_prefix(config): ...
