from . import probe as probe
from _typeshed import Incomplete

def load_config_stable(config, option): ...

MeasureAngles: Incomplete
MeasureOuterRadius: int
MeasureRidgeRadius: Incomplete
MEASURE_WEIGHT: float

def measurements_to_distances(measured_params, delta_params): ...

class DeltaCalibrate:
    printer: Incomplete
    probe_helper: Incomplete
    last_probe_positions: Incomplete
    manual_heights: Incomplete
    delta_analyze_entry: Incomplete
    last_distances: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    def save_state(self, probe_positions, distances, delta_params) -> None: ...
    def probe_finalize(self, positions) -> None: ...
    def calculate_params(self, probe_positions, distances): ...
    cmd_DELTA_CALIBRATE_help: str
    def cmd_DELTA_CALIBRATE(self, gcmd) -> None: ...
    def add_manual_height(self, height) -> None: ...
    def do_extended_calibration(self) -> None: ...
    cmd_DELTA_ANALYZE_help: str
    def cmd_DELTA_ANALYZE(self, gcmd) -> None: ...

def load_config(config): ...
