from _typeshed import Incomplete

M73_TIMEOUT: float

class DisplayStatus:
    printer: Incomplete
    expire_progress: float
    progress: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    def cmd_M73(self, gcmd) -> None: ...
    message: Incomplete
    def cmd_M117(self, gcmd) -> None: ...
    cmd_SET_DISPLAY_TEXT_help: str
    def cmd_SET_DISPLAY_TEXT(self, gcmd) -> None: ...

def load_config(config): ...
