from . import output_pin as output_pin, pulse_counter as pulse_counter
from _typeshed import Incomplete

class Fan:
    printer: Incomplete
    last_fan_value: float
    max_power: Incomplete
    kick_start_time: Incomplete
    off_below: Incomplete
    mcu_fan: Incomplete
    enable_pin: Incomplete
    gcrq: Incomplete
    tachometer: Incomplete
    def __init__(self, config, default_shutdown_speed: float = 0.0) -> None: ...
    def get_mcu(self): ...
    def set_speed(self, value, print_time=None) -> None: ...
    def set_speed_from_command(self, value) -> None: ...
    def get_status(self, eventtime): ...

class FanTachometer:
    ppr: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...

class PrinterFan:
    fan: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    def cmd_M106(self, gcmd) -> None: ...
    def cmd_M107(self, gcmd) -> None: ...

def load_config(config): ...
