from _typeshed import Incomplete

class GetStatusWrapper:
    printer: Incomplete
    eventtime: Incomplete
    cache: Incomplete
    def __init__(self, printer, eventtime=None) -> None: ...
    def __getitem__(self, val): ...
    def __contains__(self, val) -> bool: ...
    def __iter__(self): ...

class TemplateWrapper:
    printer: Incomplete
    name: Incomplete
    gcode: Incomplete
    create_template_context: Incomplete
    template: Incomplete
    def __init__(self, printer, env, name, script) -> None: ...
    def render(self, context=None): ...
    def run_gcode_from_command(self, context=None) -> None: ...

class PrinterGCodeMacro:
    printer: Incomplete
    env: Incomplete
    def __init__(self, config) -> None: ...
    def load_template(self, config, option, default=None): ...
    def create_template_context(self, eventtime=None): ...

def load_config(config): ...

class GCodeMacro:
    alias: Incomplete
    printer: Incomplete
    template: Incomplete
    gcode: Incomplete
    rename_existing: Incomplete
    cmd_desc: Incomplete
    in_script: bool
    variables: Incomplete
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    def get_status(self, eventtime): ...
    cmd_SET_GCODE_VARIABLE_help: str
    def cmd_SET_GCODE_VARIABLE(self, gcmd) -> None: ...
    def cmd(self, gcmd) -> None: ...

def load_config_prefix(config): ...
