from _typeshed import Incomplete
from typing import Any

import configfile
from gcode import GCodeCommand
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from klippy.klippy import Printer

KELVIN_TO_CELSIUS: float
MAX_HEAT_TIME: float
AMBIENT_TEMP: float
PID_PARAM_BASE: float
MAX_MAINTHREAD_TIME: float
QUELL_STALE_TIME: float
MIN_PWM_CHANGE_RATIO: float

class Heater:
    printer: Printer
    name: str
    short_name: str
    sensor: Incomplete
    min_temp: float
    max_temp: float
    pwm_delay: float
    min_extrude_temp: float
    can_extrude: bool
    max_power: float
    min_pwm_change: float
    smooth_time: float
    inv_smooth_time: float
    verify_mainthread_time: float
    lock: Incomplete
    last_temp: float
    last_temp_time: float
    next_pwm_time: float
    last_pwm_value: float
    control: Incomplete
    mcu_pwm: Incomplete
    def __init__(self, config: configfile.ConfigWrapper, sensor) -> None: ...
    def set_pwm(self, read_time: float, value: float) -> None: ...
    def temperature_callback(self, read_time: float, temp: float) -> None: ...
    def get_name(self) -> str: ...
    def get_pwm_delay(self) -> float: ...
    def get_max_power(self) -> float: ...
    def get_smooth_time(self) -> float: ...
    target_temp: float
    def set_temp(self, degrees: float) -> None: ...
    def get_temp(self, eventtime: float) -> tuple[float, float]: ...
    def check_busy(self, eventtime: float) -> bool: ...
    def set_control(self, control) -> Incomplete: ...
    def alter_target(self, target_temp: float) -> None: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...
    cmd_SET_HEATER_TEMPERATURE_help: str
    def cmd_SET_HEATER_TEMPERATURE(self, gcmd: GCodeCommand) -> None: ...

class ControlBangBang:
    heater: Heater
    heater_max_power: float
    max_delta: float
    heating: bool
    def __init__(self, heater: Heater, config: configfile.ConfigWrapper) -> None: ...
    def temperature_update(self, read_time: float, temp: float, target_temp: float) -> None: ...
    def check_busy(self, eventtime: float, smoothed_temp: float, target_temp: float) -> bool: ...

PID_SETTLE_DELTA: float
PID_SETTLE_SLOPE: float

class ControlPID:
    heater: Heater
    heater_max_power: float
    Kp: float
    Ki: float
    Kd: float
    min_deriv_time: float
    temp_integ_max: float
    prev_temp: float
    prev_temp_time: float
    prev_temp_deriv: float
    prev_temp_integ: float
    def __init__(self, heater: Heater, config: configfile.ConfigWrapper) -> None: ...
    def temperature_update(self, read_time: float, temp: float, target_temp: float) -> None: ...
    def check_busy(self, eventtime: float, smoothed_temp: float, target_temp: float) -> bool: ...

class PrinterHeaters:
    printer: Printer
    sensor_factories: dict[str, Any]
    heaters: dict[str, Heater]
    gcode_id_to_sensor: dict[str, str]
    available_heaters: list[str]
    available_sensors: list[str]
    available_monitors: list[str]
    has_started: bool
    def __init__(self, config: configfile.ConfigWrapper) -> None: ...
    have_load_sensors: bool
    def load_config(self, config: configfile.ConfigWrapper) -> None: ...
    def add_sensor_factory(self, sensor_type: str, sensor_factory) -> None: ...
    def setup_heater(self, config: configfile.ConfigWrapper, gcode_id: str | None = None) -> Heater: ...
    def get_all_heaters(self) -> list[str]: ...
    def lookup_heater(self, heater_name: str) -> Heater: ...
    def setup_sensor(self, config: configfile.ConfigWrapper) -> Incomplete: ...
    def register_sensor(self, config: configfile.ConfigWrapper, psensor, gcode_id: str | None = None) -> None: ...
    def register_monitor(self, config: configfile.ConfigWrapper) -> None: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...
    def turn_off_all_heaters(self, print_time: float = 0.0) -> None: ...
    cmd_TURN_OFF_HEATERS_help: str
    def cmd_TURN_OFF_HEATERS(self, gcmd: GCodeCommand) -> None: ...
    def cmd_M105(self, gcmd: GCodeCommand) -> None: ...
    def set_temperature(self, heater: Heater, temp: float, wait: bool = False) -> None: ...
    cmd_TEMPERATURE_WAIT_help: str
    def cmd_TEMPERATURE_WAIT(self, gcmd: GCodeCommand) -> None: ...

def load_config(config: configfile.ConfigWrapper) -> PrinterHeaters: ...
