from _typeshed import Incomplete

class HomingHeaters:
    printer: Incomplete
    disable_heaters: Incomplete
    flaky_steppers: Incomplete
    pheaters: Incomplete
    target_save: Incomplete
    def __init__(self, config) -> None: ...
    def handle_connect(self) -> None: ...
    def check_eligible(self, endstops): ...
    def handle_homing_move_begin(self, hmove) -> None: ...
    def handle_homing_move_end(self, hmove) -> None: ...

def load_config(config): ...
