from . import shaper_defs as shaper_defs
from _typeshed import Incomplete

class InputShaperParams:
    axis: Incomplete
    shaper_type: Incomplete
    damping_ratio: Incomplete
    shaper_freq: Incomplete
    def __init__(self, axis, config) -> None: ...
    def update(self, gcmd) -> None: ...
    def get_shaper(self, shaper_type=None, shaper_freq=None, damping_ratio=None, error=None): ...
    def get_status(self): ...

class AxisInputShaper:
    axis: Incomplete
    params: Incomplete
    saved: Incomplete
    def __init__(self, axis, config) -> None: ...
    def get_name(self): ...
    def get_shaper(self): ...
    def update(self, gcmd) -> None: ...
    def set_shaper_kinematics(self, sk): ...
    def is_enabled(self): ...
    def disable_shaping(self) -> None: ...
    def enable_shaping(self) -> None: ...
    def report(self, gcmd) -> None: ...

class InputShaper:
    printer: Incomplete
    toolhead: Incomplete
    shapers: Incomplete
    input_shaper_stepper_kinematics: Incomplete
    orig_stepper_kinematics: Incomplete
    def __init__(self, config) -> None: ...
    def get_shapers(self): ...
    def connect(self) -> None: ...
    def disable_shaping(self) -> None: ...
    def enable_shaping(self) -> None: ...
    cmd_SET_INPUT_SHAPER_help: str
    def cmd_SET_INPUT_SHAPER(self, gcmd) -> None: ...

def load_config(config): ...
