from . import ads1220 as ads1220, ads131m0x as ads131m0x, hx71x as hx71x
from .bulk_sensor import BatchWebhooksClient as BatchWebhooksClient
from _typeshed import Incomplete

zip_impl = zip

def select_column(data, column_idx): ...
def avg(data): ...

class ApiClientHelper:
    printer: Incomplete
    client_cbs: Incomplete
    webhooks_start_resp: Incomplete
    def __init__(self, printer) -> None: ...
    def send(self, msg) -> None: ...
    def add_client(self, client_cb) -> None: ...
    def add_mux_endpoint(self, path, key, value, webhooks_start_resp) -> None: ...

class LoadCellCommandHelper:
    printer: Incomplete
    load_cell: Incomplete
    name: Incomplete
    def __init__(self, config, load_cell) -> None: ...
    def register_commands(self, name) -> None: ...
    cmd_LOAD_CELL_TARE_help: str
    def cmd_LOAD_CELL_TARE(self, gcmd) -> None: ...
    cmd_CALIBRATE_LOAD_CELL_help: str
    def cmd_LOAD_CELL_CALIBRATE(self, gcmd) -> None: ...
    cmd_LOAD_CELL_READ_help: str
    def cmd_LOAD_CELL_READ(self, gcmd) -> None: ...
    cmd_LOAD_CELL_DIAGNOSTIC_help: str
    def cmd_LOAD_CELL_DIAGNOSTIC(self, gcmd) -> None: ...

class LoadCellGuidedCalibrationHelper:
    printer: Incomplete
    gcode: Incomplete
    load_cell: Incomplete
    tare_percent: float
    def __init__(self, printer, load_cell) -> None: ...
    def verify_no_active_calibration(self) -> None: ...
    def register_commands(self) -> None: ...
    def counts_per_gram(self, grams, cal_counts): ...
    def capacity_kg(self, counts_per_gram): ...
    def finalize(self, save_results: bool = False) -> None: ...
    cmd_ABORT_help: str
    def cmd_ABORT(self, gcmd) -> None: ...
    cmd_ACCEPT_help: str
    def cmd_ACCEPT(self, gcmd) -> None: ...
    cmd_TARE_help: str
    def cmd_TARE(self, gcmd) -> None: ...
    cmd_CALIBRATE_help: str
    def cmd_CALIBRATE(self, gcmd) -> None: ...

RETRY_DELAY: float

class LoadCellSampleCollector:
    min_time: float
    max_time: Incomplete
    min_count: Incomplete
    is_started: bool
    def __init__(self, printer, load_cell) -> None: ...
    def start_collecting(self, min_time=None) -> None: ...
    def stop_collecting(self): ...
    def collect_min(self, min_count: int = 1): ...
    def collect_until(self, print_time=None): ...

MIN_COUNTS_PER_GRAM: float

class LoadCell:
    printer: Incomplete
    config_name: Incomplete
    name: Incomplete
    sensor: Incomplete
    reference_tare_counts: Incomplete
    tare_counts: Incomplete
    counts_per_gram: Incomplete
    invert: Incomplete
    clients: Incomplete
    def __init__(self, config, sensor) -> None: ...
    def add_client(self, callback) -> None: ...
    def tare(self, tare_counts) -> None: ...
    def set_calibration(self, counts_per_gram, tare_counts) -> None: ...
    def counts_to_grams(self, sample): ...
    def saturation_range(self): ...
    def counts_to_percent(self, counts): ...
    def avg_counts(self, num_samples=None): ...
    def is_tared(self): ...
    def is_calibrated(self): ...
    def get_sensor(self): ...
    def get_reference_tare_counts(self): ...
    def get_tare_counts(self): ...
    def get_counts_per_gram(self): ...
    def get_collector(self): ...
    def get_status(self, eventtime): ...

def load_config(config): ...
def load_config_prefix(config): ...
