from . import force_move as force_move
from _typeshed import Incomplete

class ManualStepper:
    printer: Incomplete
    name: Incomplete
    can_home: bool
    rail: Incomplete
    steppers: Incomplete
    velocity: Incomplete
    accel: Incomplete
    next_cmd_time: float
    commanded_pos: float
    pos_min: Incomplete
    pos_max: Incomplete
    motion_queuing: Incomplete
    trapq: Incomplete
    trapq_append: Incomplete
    axis_gcode_id: Incomplete
    instant_corner_v: float
    gaxis_limit_velocity: float
    def __init__(self, config) -> None: ...
    def get_name(self): ...
    def sync_print_time(self) -> None: ...
    def do_enable(self, enable) -> None: ...
    def do_set_position(self, setpos) -> None: ...
    def do_move(self, movepos, speed, accel, sync: bool = True) -> None: ...
    homing_accel: Incomplete
    def do_homing_move(self, movepos, speed, accel, probe_pos, triggered, check_trigger) -> None: ...
    cmd_MANUAL_STEPPER_help: str
    def cmd_MANUAL_STEPPER(self, gcmd): ...
    gaxis_limit_accel: Incomplete
    def command_with_gcode_axis(self, gcmd) -> None: ...
    def process_move(self, print_time, move, ea_index) -> None: ...
    def check_move(self, move, ea_index) -> None: ...
    def calc_junction(self, prev_move, move, ea_index): ...
    def get_axis_gcode_id(self): ...
    def get_trapq(self): ...
    def flush_step_generation(self) -> None: ...
    def get_position(self): ...
    def set_position(self, newpos, homing_axes: str = '') -> None: ...
    def get_last_move_time(self): ...
    def dwell(self, delay) -> None: ...
    def drip_move(self, newpos, speed, drip_completion) -> None: ...
    def get_kinematics(self): ...
    def get_steppers(self): ...
    def calc_position(self, stepper_positions): ...

def load_config_prefix(config): ...
