from _typeshed import Incomplete

class PrintStats:
    gcode_move: Incomplete
    reactor: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    filename: Incomplete
    def set_current_file(self, filename) -> None: ...
    print_start_time: Incomplete
    last_pause_time: Incomplete
    last_epos: Incomplete
    state: str
    error_message: str
    def note_start(self) -> None: ...
    def note_pause(self) -> None: ...
    def note_complete(self) -> None: ...
    def note_error(self, message) -> None: ...
    def note_cancel(self) -> None: ...
    cmd_SET_PRINT_STATS_INFO_help: str
    info_total_layer: Incomplete
    info_current_layer: Incomplete
    def cmd_SET_PRINT_STATS_INFO(self, gcmd) -> None: ...
    prev_pause_duration: float
    filament_used: float
    init_duration: float
    def reset(self) -> None: ...
    total_duration: Incomplete
    def get_status(self, eventtime): ...

def load_config(config): ...
