from . import ldc1612 as ldc1612, manual_probe as manual_probe, probe as probe, trigger_analog as trigger_analog
from _typeshed import Incomplete

OUT_OF_RANGE: float

class DummyDriftCompensation:
    def get_temperature(self): ...
    def note_z_calibration_start(self) -> None: ...
    def note_z_calibration_finish(self) -> None: ...
    def adjust_freq(self, freq, temp=None): ...
    def unadjust_freq(self, freq, temp=None): ...

class EddyCalibration:
    printer: Incomplete
    drift_comp: Incomplete
    cal_freqs: Incomplete
    cal_zpos: Incomplete
    def __init__(self, config) -> None: ...
    def get_printer(self): ...
    def note_z_calibration_start(self) -> None: ...
    def note_z_calibration_finish(self) -> None: ...
    def register_drift_compensation(self, comp) -> None: ...
    def verify_calibrated(self) -> None: ...
    def get_calibration(self): ...
    def apply_calibration(self, samples) -> None: ...
    def freq_to_height(self, freq): ...
    def height_to_freq(self, height): ...

class EddyCalibrationTool:
    printer: Incomplete
    name: Incomplete
    calibration: Incomplete
    probe_speed: float
    def __init__(self, config, calibration) -> None: ...
    def do_calibration_moves(self, move_speed): ...
    def calc_freqs(self, meas): ...
    def validate_calibration_data(self, positions): ...
    def post_manual_probe(self, mpresult) -> None: ...
    cmd_EDDY_CALIBRATE_help: str
    def cmd_EDDY_CALIBRATE(self, gcmd) -> None: ...
    cmd_Z_OFFSET_APPLY_PROBE_help: str
    def cmd_Z_OFFSET_APPLY_PROBE(self, gcmd) -> None: ...

class EddyTapCalibration:
    def __init__(self, config, calibration, eddy_tap) -> None: ...
    cmd_TAP_CALIBRATE_help: str
    def cmd_TAP_CALIBRATE(self, gcmd) -> None: ...

class EddyGatherSamples:
    def __init__(self, printer, sensor_helper) -> None: ...
    def finish(self) -> None: ...
    def add_probe_request(self, cb, start_time, end_time, *args) -> None: ...
    def pull_probed(self): ...

def probe_results_from_avg(measures, toolhead_pos, calibration, offsets): ...

class TapBestFit:
    def __init__(self) -> None: ...
    def find_best_fit(self, data): ...

MAX_VALID_RAW_VALUE: int

class EddyDescend:
    def __init__(self, config, sensor_helper, calibration, probe_offsets, param_helper, trigger_analog) -> None: ...
    def start_probe_session(self, gcmd): ...
    def run_probe(self, gcmd) -> None: ...
    def pull_probed_results(self): ...
    def end_probe_session(self) -> None: ...

class EddyTap:
    def __init__(self, config, sensor_helper, param_helper, trigger_analog) -> None: ...
    def get_last_tap_info(self): ...
    def start_probe_session(self, gcmd): ...
    def run_probe(self, gcmd) -> None: ...
    def pull_probed_results(self): ...
    def end_probe_session(self) -> None: ...

class EddyScanningProbe:
    def __init__(self, config, sensor_helper, calibration, probe_offsets) -> None: ...
    def start_probe_session(self, gcmd): ...
    def run_probe(self, gcmd) -> None: ...
    def pull_probed_results(self): ...
    def end_probe_session(self) -> None: ...

class EddyProbeOffsets:
    x_offset: Incomplete
    y_offset: Incomplete
    def __init__(self, config) -> None: ...
    def get_offsets(self, gcmd=None): ...

class EddyParameterHelper:
    def __init__(self, config) -> None: ...
    def get_probe_params(self, gcmd=None): ...

class PrinterEddyProbe:
    printer: Incomplete
    calibration: Incomplete
    sensor_helper: Incomplete
    probe_offsets: Incomplete
    param_helper: Incomplete
    eddy_descend_session: Incomplete
    eddy_tap_session: Incomplete
    eddy_scan: Incomplete
    cmd_helper: Incomplete
    def __init__(self, config) -> None: ...
    def add_client(self, cb) -> None: ...
    def get_probe_params(self, gcmd=None): ...
    def get_offsets(self, gcmd=None): ...
    def get_status(self, eventtime): ...
    def start_probe_session(self, gcmd): ...
    def register_drift_compensation(self, comp) -> None: ...

def load_config_prefix(config): ...
