class MCU_counter:
    def __init__(self, printer, pin, sample_time, poll_time) -> None: ...
    def build_config(self) -> None: ...
    def setup_callback(self, cb) -> None: ...

class FrequencyCounter:
    def __init__(self, printer, pin, sample_time, poll_time) -> None: ...
    def get_frequency(self): ...
