from _typeshed import Incomplete

class error(Exception): ...

class MCU_queued_pwm:
    def __init__(self, config, pin_params) -> None: ...
    def get_mcu(self): ...
    def setup_max_duration(self, max_duration) -> None: ...
    def setup_cycle_time(self, cycle_time, hardware_pwm: bool = False) -> None: ...
    def setup_start_value(self, start_value, shutdown_value) -> None: ...
    def set_pwm(self, print_time, value) -> None: ...

class PrinterOutputPin:
    printer: Incomplete
    mcu_pin: Incomplete
    scale: Incomplete
    last_print_time: float
    last_value: Incomplete
    shutdown_value: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    cmd_SET_PIN_help: str
    def cmd_SET_PIN(self, gcmd): ...

def load_config_prefix(config): ...
