from _typeshed import Incomplete

class MCU_pwm_cycle:
    def __init__(self, pin_params, cycle_time, start_value, shutdown_value) -> None: ...
    def get_mcu(self): ...
    def set_pwm_cycle(self, print_time, value, cycle_time) -> None: ...

class PrinterOutputPWMCycle:
    printer: Incomplete
    last_print_time: float
    scale: Incomplete
    last_value: Incomplete
    shutdown_value: Incomplete
    mcu_pin: Incomplete
    last_cycle_time: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    cmd_SET_PIN_help: str
    def cmd_SET_PIN(self, gcmd): ...

def load_config_prefix(config): ...
