from _typeshed import Incomplete

class QueryEndstops:
    printer: Incomplete
    endstops: Incomplete
    last_state: Incomplete
    def __init__(self, config) -> None: ...
    def register_endstop(self, mcu_endstop, name) -> None: ...
    def get_status(self, eventtime): ...
    cmd_QUERY_ENDSTOPS_help: str
    def cmd_QUERY_ENDSTOPS(self, gcmd) -> None: ...

def load_config(config): ...
