from . import shaper_calibrate as shaper_calibrate
from _typeshed import Incomplete

class TestAxis:
    def __init__(self, axis=None, vib_dir=None) -> None: ...
    def matches(self, chip_axis): ...
    def get_dir(self): ...
    def get_name(self): ...
    def get_point(self, l): ...

class VibrationPulseTestGenerator:
    min_freq: Incomplete
    max_freq: Incomplete
    max_freq_z: Incomplete
    accel_per_hz: Incomplete
    accel_per_hz_z: Incomplete
    hz_per_sec: Incomplete
    def __init__(self, config) -> None: ...
    freq_start: Incomplete
    freq_end: Incomplete
    test_accel_per_hz: Incomplete
    test_hz_per_sec: Incomplete
    def prepare_test(self, gcmd, is_z) -> None: ...
    def gen_test(self): ...
    def get_max_freq(self): ...

class SweepingVibrationsTestGenerator:
    vibration_generator: Incomplete
    sweeping_accel: Incomplete
    sweeping_accel_z: Incomplete
    sweeping_period: Incomplete
    def __init__(self, config) -> None: ...
    test_sweeping_accel: Incomplete
    test_sweeping_period: Incomplete
    def prepare_test(self, gcmd, is_z) -> None: ...
    def gen_test(self): ...
    def get_max_freq(self): ...

def lookup_z_limits(configfile): ...

class ResonanceTestExecutor:
    printer: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    def run_test(self, test_seq, axis, gcmd) -> None: ...

class ResonanceTester:
    printer: Incomplete
    move_speed: Incomplete
    generator: Incomplete
    executor: Incomplete
    accel_chip_names: Incomplete
    max_smoothing: Incomplete
    probe_points: Incomplete
    gcode: Incomplete
    def __init__(self, config) -> None: ...
    accel_chips: Incomplete
    def connect(self) -> None: ...
    cmd_TEST_RESONANCES_help: str
    def cmd_TEST_RESONANCES(self, gcmd) -> None: ...
    cmd_SHAPER_CALIBRATE_help: str
    def cmd_SHAPER_CALIBRATE(self, gcmd) -> None: ...
    cmd_MEASURE_AXES_NOISE_help: str
    def cmd_MEASURE_AXES_NOISE(self, gcmd) -> None: ...
    def is_valid_name_suffix(self, name_suffix): ...
    def get_filename(self, base, name_suffix, axis=None, point=None, chip_name=None): ...
    def save_calibration_data(self, base_name, name_suffix, shaper_calibrate, axis, calibration_data, all_shapers=None, point=None, max_freq=None): ...

def load_config(config): ...
