from _typeshed import Incomplete

class SaveVariables:
    printer: Incomplete
    filename: Incomplete
    allVariables: Incomplete
    def __init__(self, config) -> None: ...
    def loadVariables(self) -> None: ...
    cmd_SAVE_VARIABLE_help: str
    def cmd_SAVE_VARIABLE(self, gcmd) -> None: ...
    def get_status(self, eventtime): ...

def load_config(config): ...
