from _typeshed import Incomplete
from typing import NamedTuple

SHAPER_VIBRATION_REDUCTION: float
DEFAULT_DAMPING_RATIO: float

class InputShaperCfg(NamedTuple):
    name: Incomplete
    init_func: Incomplete
    min_freq: Incomplete
    max_damping_ratio: Incomplete

class ShaperError(Exception): ...

def get_none_shaper(): ...
def get_zv_shaper(shaper_freq, damping_ratio): ...
def get_zvd_shaper(shaper_freq, damping_ratio): ...
def get_mzv_coeffs(n, t): ...
def get_mzv_shaper(shaper_freq, damping_ratio, n: int = 3, t: float = 0.0, tau: float = 0.0): ...
def get_ei_shaper(shaper_freq, damping_ratio, v_tol=...): ...
def get_2hump_ei_shaper(shaper_freq, damping_ratio): ...
def get_3hump_ei_shaper(shaper_freq, damping_ratio): ...

INPUT_SHAPERS: Incomplete

def get_shaper_cfg(shaper_name): ...
def init_shaper(shaper_name, shaper_freq, damping_ratio, error=None): ...
