from _typeshed import Incomplete

def calc_skew_factor(ac, bd, ad): ...

class PrinterSkew:
    printer: Incomplete
    name: Incomplete
    current_profile_name: str
    toolhead: Incomplete
    xy_factor: float
    xz_factor: float
    yz_factor: float
    skew_profiles: Incomplete
    next_transform: Incomplete
    def __init__(self, config) -> None: ...
    def calc_skew(self, pos): ...
    def calc_unskew(self, pos): ...
    def get_position(self): ...
    def move(self, newpos, speed) -> None: ...
    cmd_GET_CURRENT_SKEW_help: str
    def cmd_GET_CURRENT_SKEW(self, gcmd) -> None: ...
    cmd_CALC_MEASURED_SKEW_help: str
    def cmd_CALC_MEASURED_SKEW(self, gcmd) -> None: ...
    cmd_SET_SKEW_help: str
    def cmd_SET_SKEW(self, gcmd) -> None: ...
    cmd_SKEW_PROFILE_help: str
    def cmd_SKEW_PROFILE(self, gcmd) -> None: ...
    def get_status(self, eventtime): ...

def load_config(config): ...
