from _typeshed import Incomplete

class PrinterSysStats:
    last_process_time: float
    last_load_avg: float
    last_mem_avail: int
    mem_file: Incomplete
    def __init__(self, config) -> None: ...
    def stats(self, eventtime): ...
    def get_status(self, eventtime): ...

class PrinterStats:
    printer: Incomplete
    reactor: Incomplete
    stats_timer: Incomplete
    stats_cb: Incomplete
    def __init__(self, config) -> None: ...
    def handle_ready(self) -> None: ...
    def generate_stats(self, eventtime): ...

def load_config(config): ...
