from _typeshed import Incomplete

DISABLE_STALL_TIME: float

class StepperEnablePin:
    mcu_enable: Incomplete
    enable_count: Incomplete
    is_dedicated: bool
    def __init__(self, mcu_enable, enable_count) -> None: ...
    def set_enable(self, print_time) -> None: ...
    def set_disable(self, print_time) -> None: ...

def setup_enable_pin(printer, pin): ...

class EnableTracking:
    stepper: Incomplete
    enable: Incomplete
    callbacks: Incomplete
    is_enabled: bool
    def __init__(self, stepper, enable) -> None: ...
    def register_state_callback(self, callback) -> None: ...
    def motor_enable(self, print_time) -> None: ...
    def motor_disable(self, print_time) -> None: ...
    def is_motor_enabled(self): ...
    def has_dedicated_enable(self): ...

class PrinterStepperEnable:
    printer: Incomplete
    enable_lines: Incomplete
    def __init__(self, config) -> None: ...
    def register_stepper(self, config, mcu_stepper) -> None: ...
    def set_motors_enable(self, stepper_names, enable): ...
    def motor_off(self) -> None: ...
    def get_status(self, eventtime): ...
    def cmd_M18(self, gcmd) -> None: ...
    cmd_SET_STEPPER_ENABLE_help: str
    def cmd_SET_STEPPER_ENABLE(self, gcmd) -> None: ...
    def lookup_enable(self, name): ...
    def get_steppers(self): ...

def load_config(config): ...
