from . import adc_temperature as adc_temperature
from _typeshed import Incomplete

SAMPLE_TIME: float
SAMPLE_COUNT: int
REPORT_TIME: float
RANGE_CHECK_COUNT: int

class PrinterTemperatureMCU:
    printer: Incomplete
    base_temperature: Incomplete
    temp1: Incomplete
    min_temp: float
    debug_read_cmd: Incomplete
    adc1: Incomplete
    temp2: Incomplete
    adc2: Incomplete
    mcu_adc: Incomplete
    diag_helper: Incomplete
    def __init__(self, config) -> None: ...
    temperature_callback: Incomplete
    def setup_callback(self, temperature_callback) -> None: ...
    def get_report_time_delta(self): ...
    max_temp: Incomplete
    def setup_minmax(self, min_temp, max_temp) -> None: ...
    def adc_callback(self, samples) -> None: ...
    def calc_temp(self, adc): ...
    def calc_adc(self, temp): ...
    def calc_base(self, temp, adc): ...
    mcu_type: Incomplete
    slope: Incomplete
    def handle_mcu_identify(self) -> None: ...
    def config_unknown(self) -> None: ...
    def config_rp2040(self) -> None: ...
    def config_sam3(self) -> None: ...
    def config_sam4(self) -> None: ...
    def config_same70(self) -> None: ...
    def config_samd21(self, addr: int = 8413232): ...
    def config_samd51(self) -> None: ...
    def config_stm32f1(self) -> None: ...
    def config_stm32f2(self) -> None: ...
    def config_stm32f4(
        self, addr1: int = 536836652, addr2: int = 536836654
    ) -> None: ...
    def config_stm32f0x2(self) -> None: ...
    def config_stm32f070(self) -> None: ...
    def config_stm32g0(self) -> None: ...
    def config_stm32h723(self) -> None: ...
    def config_stm32h7(self) -> None: ...
    def read16(self, addr): ...
    def read32(self, addr): ...

def load_config(config) -> None: ...
