from . import manual_probe as manual_probe
from _typeshed import Incomplete

KELVIN_TO_CELSIUS: float

class Polynomial2d:
    a: Incomplete
    b: Incomplete
    c: Incomplete
    def __init__(self, a, b, c) -> None: ...
    def __call__(self, xval): ...
    def get_coefs(self): ...
    @classmethod
    def fit(cls, coords): ...

class TemperatureProbe:
    name: Incomplete
    printer: Incomplete
    gcode: Incomplete
    speed: Incomplete
    horizontal_move_z: Incomplete
    resting_z: Incomplete
    cal_pos: Incomplete
    cal_bed_temp: Incomplete
    cal_extruder_temp: Incomplete
    cal_extruder_z: Incomplete
    inv_smooth_time: Incomplete
    min_temp: Incomplete
    max_temp: Incomplete
    sensor: Incomplete
    last_temp_read_time: float
    last_measurement: Incomplete
    cal_helper: Incomplete
    next_auto_temp: float
    target_temp: int
    expected_count: int
    sample_count: int
    in_calibration: bool
    step: float
    last_zero_pos: Incomplete
    total_expansion: int
    start_pos: Incomplete
    def __init__(self, config) -> None: ...
    def get_temp(self, eventtime=None): ...
    cmd_TEMPERATURE_PROBE_CALIBRATE_help: str
    def cmd_TEMPERATURE_PROBE_CALIBRATE(self, gcmd) -> None: ...
    cmd_TEMPERATURE_PROBE_NEXT_help: str
    def cmd_TEMPERATURE_PROBE_NEXT(self, gcmd) -> None: ...
    cmd_TEMPERATURE_PROBE_COMPLETE_help: str
    def cmd_TEMPERATURE_PROBE_COMPLETE(self, gcmd) -> None: ...
    cmd_TEMPERATURE_PROBE_ABORT_help: str
    def cmd_TEMPERATURE_PROBE_ABORT(self, gcmd) -> None: ...
    cmd_TEMPERATURE_PROBE_ENABLE_help: str
    def cmd_TEMPERATURE_PROBE_ENABLE(self, gcmd) -> None: ...
    def is_in_calibration(self): ...
    def get_status(self, eventtime=None): ...
    def stats(self, eventtime): ...

DRIFT_SAMPLE_COUNT: int

class EddyDriftCompensation:
    printer: Incomplete
    temp_sensor: Incomplete
    name: Incomplete
    cal_temp: Incomplete
    drift_calibration: Incomplete
    calibration_samples: Incomplete
    max_valid_temp: Incomplete
    dc_min_temp: Incomplete
    min_freq: float
    enabled: Incomplete
    def __init__(self, config, sensor) -> None: ...
    def is_enabled(self): ...
    def set_enabled(self, gcmd) -> None: ...
    def note_z_calibration_start(self) -> None: ...
    def note_z_calibration_finish(self) -> None: ...
    def collect_sample(self, mpresult, tool_zero_z, speeds): ...
    def start_calibration(self) -> None: ...
    def finish_calibration(self, success) -> None: ...
    def adjust_freq(self, freq, origin_temp=None): ...
    def unadjust_freq(self, freq, dest_temp=None): ...
    def get_temperature(self): ...

def load_config_prefix(config): ...
