from . import adc_temperature as adc_temperature
from _typeshed import Incomplete

KELVIN_TO_CELSIUS: float

class Thermistor:
    pullup: Incomplete
    inline_resistor: Incomplete
    c1: float
    def __init__(self, pullup, inline_resistor) -> None: ...
    c3: Incomplete
    c2: Incomplete
    def setup_coefficients(self, t1, r1, t2, r2, t3, r3, name: str = "") -> None: ...
    def setup_coefficients_beta(self, t1, r1, beta) -> None: ...
    def calc_temp(self, adc): ...
    def calc_adc(self, temp): ...

def PrinterThermistor(config, params): ...

class CustomThermistor:
    name: Incomplete
    params: Incomplete
    def __init__(self, config) -> None: ...
    def create(self, config): ...

def load_config_prefix(config) -> None: ...
