from . import probe as probe
from _typeshed import Incomplete

class ZAdjustHelper:
    printer: Incomplete
    name: Incomplete
    z_count: Incomplete
    z_steppers: Incomplete
    def __init__(self, config, z_count) -> None: ...
    def handle_connect(self) -> None: ...
    def adjust_steppers(self, adjustments, speed): ...

class ZAdjustStatus:
    applied: bool
    def __init__(self, printer) -> None: ...
    def check_retry_result(self, retry_result): ...
    def reset(self) -> None: ...
    def get_status(self, eventtime): ...

class RetryHelper:
    gcode: Incomplete
    default_max_retries: Incomplete
    default_retry_tolerance: Incomplete
    value_label: str
    error_msg_extra: Incomplete
    def __init__(self, config, error_msg_extra: str = '') -> None: ...
    max_retries: Incomplete
    retry_tolerance: Incomplete
    current_retry: int
    previous: Incomplete
    increasing: int
    def start(self, gcmd) -> None: ...
    def check_increase(self, error): ...
    def check_retry(self, z_positions): ...

class ZTilt:
    printer: Incomplete
    z_positions: Incomplete
    retry_helper: Incomplete
    probe_helper: Incomplete
    z_status: Incomplete
    z_helper: Incomplete
    def __init__(self, config) -> None: ...
    cmd_Z_TILT_ADJUST_help: str
    def cmd_Z_TILT_ADJUST(self, gcmd) -> None: ...
    def probe_finalize(self, positions): ...
    def get_status(self, eventtime): ...

def load_config(config): ...
