from _typeshed import Incomplete
from typing import Any


class ExtruderStepper:
    printer: Incomplete
    name: Incomplete
    pressure_advance: float
    config_pa: Incomplete
    config_smooth_time: Incomplete
    stepper: Incomplete
    sk_extruder: Incomplete
    motion_queue: Incomplete
    def __init__(self, config) -> None: ...
    def get_status(self, eventtime): ...
    def find_past_position(self, print_time: float) -> float: ...
    def sync_to_extruder(self, extruder_name) -> None: ...
    cmd_SET_PRESSURE_ADVANCE_help: str
    def cmd_default_SET_PRESSURE_ADVANCE(self, gcmd) -> None: ...
    def cmd_SET_PRESSURE_ADVANCE(self, gcmd) -> None: ...
    cmd_SET_E_ROTATION_DISTANCE_help: str
    def cmd_SET_E_ROTATION_DISTANCE(self, gcmd) -> None: ...
    cmd_SYNC_EXTRUDER_MOTION_help: str
    def cmd_SYNC_EXTRUDER_MOTION(self, gcmd) -> None: ...

class PrinterExtruder:
    printer: Incomplete
    name: Incomplete
    last_position: float
    heater: Incomplete
    nozzle_diameter: Incomplete
    filament_area: Incomplete
    max_extrude_ratio: Incomplete
    max_e_velocity: Incomplete
    max_e_accel: Incomplete
    max_e_dist: Incomplete
    instant_corner_v: Incomplete
    motion_queuing: Incomplete
    trapq: Incomplete
    trapq_append: Incomplete
    extruder_stepper: Incomplete
    def __init__(self, config, extruder_num) -> None: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...
    def get_name(self) -> str: ...
    def get_heater(self) -> Any: ...
    def get_trapq(self) -> Incomplete: ...
    def get_axis_gcode_id(self) -> str: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...
    def check_move(self, move, ea_index) -> None: ...
    def calc_junction(self, prev_move, move, ea_index): ...
    def process_move(self, print_time, move, ea_index) -> None: ...
    def find_past_position(self, print_time: float) -> float: ...
    def cmd_M104(self, gcmd, wait: bool = False) -> None: ...
    def cmd_M109(self, gcmd) -> None: ...
    cmd_ACTIVATE_EXTRUDER_help: str
    def cmd_ACTIVATE_EXTRUDER(self, gcmd) -> None: ...

class DummyExtruder:
    printer: Incomplete
    def __init__(self, printer) -> None: ...
    def check_move(self, move, ea_index) -> None: ...
    def find_past_position(self, print_time: float) -> float: ...
    def calc_junction(self, prev_move, move, ea_index): ...
    def get_name(self) -> str: ...
    def get_heater(self) -> None: ...
    def get_trapq(self) -> None: ...
    def get_axis_gcode_id(self) -> str: ...

def add_printer_objects(config) -> None: ...
