from . import idex_modes as idex_modes
from _typeshed import Incomplete
from typing import Any

import configfile
from gcode import GCodeCommand
from stepper import MCU_stepper
from toolhead import ToolHead
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from klippy.klippy import Printer

VALID_AXES: Incomplete

class MainCarriage:
    rail: Incomplete
    axis_name: Incomplete
    axis: Incomplete
    dual_carriage: Incomplete
    def __init__(self, config) -> None: ...
    def get_name(self): ...
    def get_axis(self): ...
    def get_rail(self): ...
    def add_stepper(self, kin_stepper) -> None: ...
    def is_active(self): ...
    def set_dual_carriage(self, carriage) -> None: ...
    def get_dual_carriage(self): ...

class ExtraCarriage:
    name: Incomplete
    primary_carriage: Incomplete
    endstop_pin: Incomplete
    def __init__(self, config, carriages) -> None: ...
    def get_name(self): ...
    def get_axis(self): ...
    def get_rail(self): ...
    def add_stepper(self, kin_stepper) -> None: ...

class DualCarriage:
    printer: Incomplete
    rail: Incomplete
    primary_carriage_name: Incomplete
    axis_name: Incomplete
    axis: Incomplete
    safe_dist: Incomplete
    primary_carriage: Incomplete
    config_error: Incomplete
    def __init__(self, config) -> None: ...
    def resolve_primary_carriage(self, carriages) -> None: ...
    def get_name(self): ...
    def get_axis(self): ...
    def get_rail(self): ...
    def get_safe_dist(self): ...
    def get_dc_module(self): ...
    def is_active(self): ...
    dual_carriage: Incomplete
    def set_dual_carriage(self, carriage) -> None: ...
    def get_dual_carriage(self): ...
    def get_primary_carriage(self): ...
    def add_stepper(self, kin_stepper) -> None: ...

class GenericCartesianKinematics:
    printer: Printer
    dc_module: idex_modes.DualCarriages | None
    max_z_velocity: float
    max_z_accel: float
    limits: list[tuple[float, float]]
    def __init__(
        self, toolhead: ToolHead, config: configfile.ConfigWrapper
    ) -> None: ...
    def get_steppers(self) -> list[MCU_stepper]: ...
    def calc_position(self, stepper_positions: dict[str, float]) -> list[float]: ...
    def update_limits(self, i: int, range: tuple[float, float]) -> None: ...
    def set_position(self, newpos: list[float], homing_axes: str) -> None: ...
    def clear_homing_state(self, clear_axes: str) -> None: ...
    def home_axis(self, homing_state, axis: int, rail) -> None: ...
    def home(self, homing_state) -> None: ...
    def check_move(self, move) -> None: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...
    cmd_SET_STEPPER_CARRIAGES_help: str
    def cmd_SET_STEPPER_CARRIAGES(self, gcmd: GCodeCommand) -> None: ...

def load_kinematics(
    toolhead: ToolHead, config: configfile.ConfigWrapper
) -> GenericCartesianKinematics: ...
