from _typeshed import Incomplete

def parse_carriages_string(carriages_str, printer_carriages, parse_error): ...

class KinematicStepper:
    printer: Incomplete
    stepper: Incomplete
    stepper_sk: Incomplete
    def __init__(self, config, printer_carriages) -> None: ...
    def get_name(self, short: bool = False): ...
    def get_stepper(self): ...
    def get_kin_coeffs(self): ...
    def get_active_axes(self): ...
    def get_carriages(self): ...
    kin_coeffs: Incomplete
    def update_kin_coeffs(self, kin_coeffs) -> None: ...
    carriages: Incomplete
    def update_carriages(self, carriages_str, printer_carriages, report_error) -> None: ...
    def set_position(self, coord) -> None: ...
