from _typeshed import Incomplete

class NoneKinematics:
    axes_minmax: Incomplete
    def __init__(self, toolhead, config) -> None: ...
    def get_steppers(self): ...
    def calc_position(self, stepper_positions): ...
    def set_position(self, newpos, homing_axes) -> None: ...
    def clear_homing_state(self, clear_axes) -> None: ...
    def home(self, homing_state) -> None: ...
    def check_move(self, move) -> None: ...
    def get_status(self, eventtime): ...

def load_kinematics(toolhead, config): ...
