from .. import bus as bus
from _typeshed import Incomplete

LINE_LENGTH_DEFAULT: int
LINE_LENGTH_OPTIONS: Incomplete
TextGlyphs: Incomplete

class hd44780_spi:
    printer: Incomplete
    hd44780_protocol_init: Incomplete
    spi: Incomplete
    mcu: Incomplete
    data_mask: Incomplete
    command_mask: int
    enable_mask: Incomplete
    icons: Incomplete
    line_length: Incomplete
    text_framebuffers: Incomplete
    glyph_framebuffer: Incomplete
    all_framebuffers: Incomplete
    def __init__(self, config) -> None: ...
    def send_4_bits(self, cmd, is_data, minclock) -> None: ...
    def send(self, cmds, is_data: bool = False, minclock: int = 0) -> None: ...
    def flush(self) -> None: ...
    def init(self) -> None: ...
    def write_text(self, x, y, data) -> None: ...
    def set_glyphs(self, glyphs) -> None: ...
    def write_glyph(self, x, y, glyph_name): ...
    def write_graphics(self, x, y, data) -> None: ...
    def clear(self) -> None: ...
    def get_dimensions(self): ...
