from _typeshed import Incomplete

BACKGROUND_PRIORITY_CLOCK: int
LINE_LENGTH_DEFAULT: int
LINE_LENGTH_OPTIONS: Incomplete
TextGlyphs: Incomplete
HD44780_DELAY: float

class HD44780:
    printer: Incomplete
    hd44780_protocol_init: Incomplete
    line_length: Incomplete
    pins: Incomplete
    mcu: Incomplete
    oid: Incomplete
    send_data_cmd: Incomplete
    icons: Incomplete
    text_framebuffers: Incomplete
    glyph_framebuffer: Incomplete
    all_framebuffers: Incomplete
    def __init__(self, config) -> None: ...
    send_cmds_cmd: Incomplete
    def build_config(self) -> None: ...
    def send(self, cmds, is_data: bool = False) -> None: ...
    def flush(self) -> None: ...
    def init(self) -> None: ...
    def write_text(self, x, y, data) -> None: ...
    def set_glyphs(self, glyphs) -> None: ...
    def write_glyph(self, x, y, glyph_name): ...
    def write_graphics(self, x, y, data) -> None: ...
    def clear(self) -> None: ...
    def get_dimensions(self): ...
