from _typeshed import Incomplete

LONG_PRESS_DURATION: float
TIMER_DELAY: float

class MenuKeys:
    printer: Incomplete
    reactor: Incomplete
    callback: Incomplete
    encoder_fast_rate: Incomplete
    last_encoder_cw_eventtime: int
    last_encoder_ccw_eventtime: int
    is_short_click: bool
    click_timer: Incomplete
    def __init__(self, config, callback) -> None: ...
    def register_button(
        self, config, name, callback, push_only: bool = True
    ) -> None: ...
    def encoder_cw_callback(self, eventtime) -> None: ...
    def encoder_ccw_callback(self, eventtime) -> None: ...
    def long_click_event(self, eventtime): ...
    def click_callback(self, eventtime, state) -> None: ...
    def back_callback(self, eventtime) -> None: ...
    def up_callback(self, eventtime) -> None: ...
    def down_callback(self, eventtime) -> None: ...
    def kill_callback(self, eventtime) -> None: ...
