from . import font8x14 as font8x14
from .. import bus as bus
from _typeshed import Incomplete

BACKGROUND_PRIORITY_CLOCK: int
ST7920_CMD_DELAY: float
ST7920_SYNC_DELAY: float
TextGlyphs: Incomplete
CharGlyphs: Incomplete

class DisplayBase:
    text_framebuffer: Incomplete
    glyph_framebuffer: Incomplete
    graphics_framebuffers: Incomplete
    all_framebuffers: Incomplete
    cached_glyphs: Incomplete
    icons: Incomplete
    def __init__(self) -> None: ...
    def flush(self) -> None: ...
    def init(self) -> None: ...
    def cache_glyph(self, glyph_name, base_glyph_name, glyph_id) -> None: ...
    def set_glyphs(self, glyphs) -> None: ...
    def write_text(self, x, y, data) -> None: ...
    def write_graphics(self, x, y, data) -> None: ...
    def write_glyph(self, x, y, glyph_name): ...
    def clear(self) -> None: ...
    def get_dimensions(self): ...

class ST7920(DisplayBase):
    pins: Incomplete
    mcu: Incomplete
    oid: Incomplete
    send_data_cmd: Incomplete
    is_extended: bool
    def __init__(self, config) -> None: ...
    send_cmds_cmd: Incomplete
    def build_config(self) -> None: ...
    def send(self, cmds, is_data: bool = False, is_extended: bool = False) -> None: ...

class EnableHelper:
    en_pin: Incomplete
    def __init__(self, pin_desc, spi) -> None: ...
    def init(self) -> None: ...

class EmulatedST7920(DisplayBase):
    spi: Incomplete
    en_helper: Incomplete
    en_set: bool
    is_extended: bool
    def __init__(self, config) -> None: ...
    def send(self, cmds, is_data: bool = False, is_extended: bool = False) -> None: ...
