from . import font8x14 as font8x14
from .. import bus as bus
from _typeshed import Incomplete

BACKGROUND_PRIORITY_CLOCK: int
TextGlyphs: Incomplete

class DisplayBase:
    send: Incomplete
    columns: Incomplete
    x_offset: Incomplete
    vram: Incomplete
    all_framebuffers: Incomplete
    font: Incomplete
    icons: Incomplete
    def __init__(self, io, columns: int = 128, x_offset: int = 0) -> None: ...
    def flush(self) -> None: ...
    def set_glyphs(self, glyphs) -> None: ...
    def write_text(self, x, y, data) -> None: ...
    def write_graphics(self, x, y, data) -> None: ...
    def write_glyph(self, x, y, glyph_name): ...
    def clear(self) -> None: ...
    def get_dimensions(self): ...

class SPI4wire:
    spi: Incomplete
    mcu_dc: Incomplete
    def __init__(self, config, data_pin_name) -> None: ...
    def send(self, cmds, is_data: bool = False) -> None: ...

class I2C:
    i2c: Incomplete
    def __init__(self, config, default_addr) -> None: ...
    def send(self, cmds, is_data: bool = False) -> None: ...

class ResetHelper:
    mcu_reset: Incomplete
    def __init__(self, pin_desc, io_bus) -> None: ...
    def init(self) -> None: ...

class UC1701(DisplayBase):
    contrast: Incomplete
    reset: Incomplete
    def __init__(self, config) -> None: ...
    def init(self) -> None: ...

class SSD1306(DisplayBase):
    reset: Incomplete
    contrast: Incomplete
    vcomh: Incomplete
    invert: Incomplete
    def __init__(self, config, columns: int = 128, x_offset: int = 0) -> None: ...
    def init(self) -> None: ...

class SH1106(SSD1306):
    def __init__(self, config) -> None: ...
