def coordinate_descent(adj_params, params, error_func): ...
def background_coordinate_descent(printer, adj_params, params, error_func): ...
def trilateration(sphere_coords, radius2): ...
def matrix_cross(m1, m2): ...
def matrix_dot(m1, m2): ...
def matrix_magsq(m1): ...
def matrix_add(m1, m2): ...
def matrix_sub(m1, m2): ...
def matrix_mul(m1, s): ...
def mat_transp(a): ...
def mat_mat_mul(a, b): ...
def mat_mul_transp(a): ...
def gaussian_solve(a, rhs, allow_underdetermined: bool = False): ...
def pseudo_inverse(m): ...
def solve_linear_equations(eqs, ans, allow_underdetermined: bool = False): ...
