from . import idex_modes as idex_modes
from _typeshed import Incomplete
from typing import Any

from klippy import configfile
from klippy.stepper import GenericPrinterRail, MCU_stepper
from klippy.toolhead import ToolHead

class CartKinematics:
    printer: Incomplete
    dual_carriage_axis: int | None
    dual_carriage_rails: list[GenericPrinterRail]
    rails: list[GenericPrinterRail]
    axes_min: list[float]
    axes_max: list[float]
    dc_module: idex_modes.DualCarriages | None
    max_z_velocity: float
    max_z_accel: float
    limits: list[tuple[float, float]]
    def __init__(
        self, toolhead: ToolHead, config: configfile.ConfigWrapper
    ) -> None: ...
    def get_steppers(self) -> list[MCU_stepper]: ...
    def calc_position(self, stepper_positions: dict[str, float]) -> list[float]: ...
    def update_limits(self, i: int, range: tuple[float, float]) -> None: ...
    def set_position(self, newpos: list[float], homing_axes: str) -> None: ...
    def clear_homing_state(self, clear_axes: str) -> None: ...
    def home_axis(self, homing_state, axis: int, rail: GenericPrinterRail) -> None: ...
    def home(self, homing_state) -> None: ...
    def check_move(self, move) -> None: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...

def load_kinematics(
    toolhead: ToolHead, config: configfile.ConfigWrapper
) -> CartKinematics: ...
