from _typeshed import Incomplete

SLOW_RATIO: float
MIN_ANGLE: float

class DeltesianKinematics:
    rails: Incomplete
    limits: Incomplete
    home_z: Incomplete
    slow_x2: Incomplete
    very_slow_x2: Incomplete
    max_z_velocity: Incomplete
    max_z_accel: Incomplete
    axes_min: Incomplete
    axes_max: Incomplete
    homed_axis: Incomplete
    def __init__(self, toolhead, config) -> None: ...
    def get_steppers(self): ...
    def calc_position(self, stepper_positions): ...
    def set_position(self, newpos, homing_axes) -> None: ...
    def clear_homing_state(self, clear_axes) -> None: ...
    def home(self, homing_state) -> None: ...
    def check_move(self, move) -> None: ...
    def get_status(self, eventtime): ...

def load_kinematics(toolhead, config): ...
