from _typeshed import Incomplete

SLOW_RATIO: float

class DeltaKinematics:
    rails: Incomplete
    max_z_velocity: Incomplete
    max_z_accel: Incomplete
    radius: Incomplete
    arm_lengths: Incomplete
    arm2: Incomplete
    abs_endstops: Incomplete
    angles: Incomplete
    towers: Incomplete
    need_home: bool
    limit_xy2: float
    home_position: Incomplete
    max_z: Incomplete
    min_z: Incomplete
    limit_z: Incomplete
    min_arm_length: Incomplete
    min_arm2: Incomplete
    slow_xy2: Incomplete
    very_slow_xy2: Incomplete
    max_xy2: Incomplete
    axes_min: Incomplete
    axes_max: Incomplete
    def __init__(self, toolhead, config) -> None: ...
    def get_steppers(self): ...
    def calc_position(self, stepper_positions): ...
    def set_position(self, newpos, homing_axes) -> None: ...
    def clear_homing_state(self, clear_axes) -> None: ...
    def home(self, homing_state) -> None: ...
    def check_move(self, move) -> None: ...
    def get_status(self, eventtime): ...
    def get_calibration(self): ...

class DeltaCalibration:
    radius: Incomplete
    angles: Incomplete
    arms: Incomplete
    endstops: Incomplete
    stepdists: Incomplete
    towers: Incomplete
    abs_endstops: Incomplete
    def __init__(self, radius, angles, arms, endstops, stepdists) -> None: ...
    def coordinate_descent_params(self, is_extended): ...
    def new_calibration(self, params): ...
    def get_position_from_stable(self, stable_position): ...
    def calc_stable_position(self, coord): ...
    def save_state(self, configfile) -> None: ...

def load_kinematics(toolhead, config): ...
