from . import idex_modes as idex_modes
from _typeshed import Incomplete

class HybridCoreXZKinematics:
    printer: Incomplete
    rails: Incomplete
    axes_min: Incomplete
    axes_max: Incomplete
    dc_module: Incomplete
    max_z_velocity: Incomplete
    max_z_accel: Incomplete
    limits: Incomplete
    def __init__(self, toolhead, config) -> None: ...
    def get_steppers(self): ...
    def calc_position(self, stepper_positions): ...
    def update_limits(self, i, range) -> None: ...
    def set_position(self, newpos, homing_axes) -> None: ...
    def clear_homing_state(self, clear_axes) -> None: ...
    def home_axis(self, homing_state, axis, rail) -> None: ...
    def home(self, homing_state) -> None: ...
    def check_move(self, move) -> None: ...
    def get_status(self, eventtime): ...

def load_kinematics(toolhead, config): ...
