from _typeshed import Incomplete

INACTIVE: str
PRIMARY: str
COPY: str
MIRROR: str

class DualCarriages:
    VALID_MODES: Incomplete
    printer: Incomplete
    primary_rails: Incomplete
    dual_rails: Incomplete
    dc_rails: Incomplete
    saved_states: Incomplete
    axes: Incomplete
    def __init__(self, printer, primary_rails, dual_rails, axes, safe_dist) -> None: ...
    def get_axes(self): ...
    def get_primary_rail(self, axis): ...
    def get_dc_rail_wrapper(self, rail): ...
    def get_transform(self, rail): ...
    def is_active(self, rail): ...
    def toggle_active_dc_rail(self, target_dc) -> None: ...
    def home(self, homing_state, axis) -> None: ...
    def get_status(self, eventtime=None): ...
    def get_kin_range(self, toolhead, axis): ...
    def get_dc_order(self, first_dc, second_dc): ...
    def activate_dc_mode(self, dc, mode) -> None: ...
    cmd_SET_DUAL_CARRIAGE_help: str
    def cmd_SET_DUAL_CARRIAGE(self, gcmd) -> None: ...
    cmd_SAVE_DUAL_CARRIAGE_STATE_help: str
    def cmd_SAVE_DUAL_CARRIAGE_STATE(self, gcmd) -> None: ...
    def save_dual_carriage_state(self): ...
    cmd_RESTORE_DUAL_CARRIAGE_STATE_help: str
    def cmd_RESTORE_DUAL_CARRIAGE_STATE(self, gcmd) -> None: ...
    def restore_dual_carriage_state(
        self, saved_state, move, move_speed: float = 0.0
    ) -> None: ...

class DualCarriagesRail:
    ENC_AXES: Incomplete
    printer: Incomplete
    rail: Incomplete
    dual_rail: Incomplete
    sks: Incomplete
    axis: Incomplete
    safe_dist: Incomplete
    mode: Incomplete
    offset: float
    scale: Incomplete
    def __init__(self, printer, rail, dual_rail, axis, safe_dist, active) -> None: ...
    def get_name(self): ...
    def is_active(self): ...
    def get_axis_position(self, position): ...
    def apply_transform(self) -> None: ...
    def activate(self, mode, position, old_position=None) -> None: ...
    def inactivate(self, position) -> None: ...
    def override_axis_scaling(self, new_scale, position) -> None: ...
