from _typeshed import Incomplete

class RotaryDeltaKinematics:
    rails: Incomplete
    max_z_velocity: Incomplete
    calibration: Incomplete
    need_home: bool
    limit_xy2: float
    home_position: Incomplete
    max_z: Incomplete
    min_z: Incomplete
    max_xy2: Incomplete
    limit_z: Incomplete
    axes_min: Incomplete
    axes_max: Incomplete
    def __init__(self, toolhead, config) -> None: ...
    def get_steppers(self): ...
    def calc_position(self, stepper_positions): ...
    def set_position(self, newpos, homing_axes) -> None: ...
    def clear_homing_state(self, clear_axes) -> None: ...
    def home(self, homing_state) -> None: ...
    def check_move(self, move) -> None: ...
    def get_status(self, eventtime): ...
    def get_calibration(self): ...

class RotaryDeltaCalibration:
    shoulder_radius: Incomplete
    shoulder_height: Incomplete
    angles: Incomplete
    upper_arms: Incomplete
    lower_arms: Incomplete
    endstops: Incomplete
    stepdists: Incomplete
    sks: Incomplete
    abs_endstops: Incomplete
    def __init__(
        self,
        shoulder_radius,
        shoulder_height,
        angles,
        upper_arms,
        lower_arms,
        endstops,
        stepdists,
    ) -> None: ...
    def coordinate_descent_params(self, is_extended): ...
    def new_calibration(self, params): ...
    def elbow_coord(self, elbow_id, spos): ...
    def actuator_to_cartesian(self, spos): ...
    def get_position_from_stable(self, stable_position): ...
    def calc_stable_position(self, coord): ...
    def save_state(self, configfile) -> None: ...

def load_kinematics(toolhead, config): ...
