from . import aip31068_spi as aip31068_spi, hd44780 as hd44780, hd44780_spi as hd44780_spi, menu as menu, st7920 as st7920, uc1701 as uc1701
from _typeshed import Incomplete

REDRAW_TIME: float
REDRAW_MIN_TIME: float
LCD_chips: Incomplete

class DisplayTemplate:
    printer: Incomplete
    name: Incomplete
    params: Incomplete
    template: Incomplete
    def __init__(self, config) -> None: ...
    def get_params(self): ...
    def render(self, context, **kwargs): ...

class DisplayGroup:
    data_items: Incomplete
    def __init__(self, config, name, data_configs) -> None: ...
    def show(self, display, templates, eventtime): ...

class PrinterDisplayTemplate:
    printer: Incomplete
    display_templates: Incomplete
    display_data_groups: Incomplete
    display_glyphs: Incomplete
    def __init__(self, config) -> None: ...
    def get_display_templates(self): ...
    def get_display_data_groups(self): ...
    def get_display_glyphs(self): ...
    def load_config(self, config) -> None: ...

def lookup_display_templates(config): ...

class PrinterLCD:
    printer: Incomplete
    reactor: Incomplete
    lcd_chip: Incomplete
    menu: Incomplete
    display_templates: Incomplete
    display_data_groups: Incomplete
    show_data_group: Incomplete
    screen_update_timer: Incomplete
    redraw_request_pending: bool
    redraw_time: float
    def __init__(self, config) -> None: ...
    def get_dimensions(self): ...
    def handle_ready(self) -> None: ...
    def screen_update_event(self, eventtime): ...
    def request_redraw(self) -> None: ...
    def draw_text(self, row, col, mixed_text, eventtime): ...
    def draw_progress_bar(self, row, col, width, value): ...
    cmd_SET_DISPLAY_GROUP_help: str
    def cmd_SET_DISPLAY_GROUP(self, gcmd) -> None: ...

def load_config(config): ...
