from . import menu_keys as menu_keys
from _typeshed import Incomplete

class sentinel: ...
class error(Exception): ...

class MenuElement:
    def __init__(self, manager, config, **kwargs) -> None: ...
    def init(self) -> None: ...
    def is_editing(self): ...
    def is_scrollable(self): ...
    def is_enabled(self): ...
    def start_editing(self) -> None: ...
    def stop_editing(self) -> None: ...
    def get_context(self, cxt=None): ...
    def eval_enable(self, context): ...
    def select(self) -> None: ...
    def heartbeat(self, eventtime) -> None: ...
    def need_scroller(self, value) -> None: ...
    def render_name(self, selected: bool = False): ...
    def get_ns(self, name: str = '.'): ...
    def send_event(self, event, *args): ...
    def get_script(self, name): ...
    def run_script(self, name, **kwargs): ...
    @property
    def cursor(self): ...
    @property
    def manager(self): ...
    @property
    def index(self): ...

class MenuContainer(MenuElement):
    def __init__(self, manager, config, **kwargs) -> None: ...
    def init(self) -> None: ...
    def is_accepted(self, item): ...
    def is_editing(self): ...
    def stop_editing(self) -> None: ...
    def lookup_item(self, item): ...
    def index_of(self, item, look_inside: bool = False): ...
    def add_parents(self, parents) -> None: ...
    def assert_recursive_relation(self, parents=None) -> None: ...
    def insert_item(self, s, index=None) -> None: ...
    def populate(self) -> None: ...
    def update_items(self) -> None: ...
    def init_selection(self) -> None: ...
    def select_at(self, index): ...
    def select_item(self, needle): ...
    def selected_item(self): ...
    def select_next(self): ...
    def select_prev(self): ...
    def draw_container(self, nrows, eventtime) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, key): ...
    @property
    def selected(self): ...

class MenuDisabled(MenuElement):
    def __init__(self, manager, config, **kwargs) -> None: ...
    def is_enabled(self): ...

class MenuCommand(MenuElement):
    def __init__(self, manager, config, **kwargs) -> None: ...

class MenuInput(MenuCommand):
    def __init__(self, manager, config, **kwargs) -> None: ...
    def init(self) -> None: ...
    def is_scrollable(self): ...
    def is_editing(self): ...
    def stop_editing(self) -> None: ...
    def start_editing(self) -> None: ...
    def heartbeat(self, eventtime) -> None: ...
    def get_context(self, cxt=None): ...
    def is_enabled(self): ...
    def inc_value(self, fast_rate: bool = False) -> None: ...
    def dec_value(self, fast_rate: bool = False) -> None: ...
    def handle_script_click(self) -> None: ...

class MenuList(MenuContainer):
    def __init__(self, manager, config, **kwargs) -> None: ...
    def draw_container(self, nrows, eventtime) -> None: ...

class MenuVSDList(MenuList):
    def __init__(self, manager, config, **kwargs) -> None: ...

menu_items: Incomplete
TIMER_DELAY: float

class MenuManager:
    running: bool
    menuitems: Incomplete
    menustack: Incomplete
    children: Incomplete
    display: Incomplete
    printer: Incomplete
    pconfig: Incomplete
    gcode: Incomplete
    gcode_queue: Incomplete
    context: Incomplete
    root: Incomplete
    timeout: Incomplete
    timer: int
    gcode_macro: Incomplete
    def __init__(self, config, display) -> None: ...
    def handle_ready(self) -> None: ...
    def timer_event(self, eventtime): ...
    def timeout_check(self, eventtime) -> None: ...
    def send_event(self, event, *args): ...
    def is_running(self): ...
    def begin(self, eventtime) -> None: ...
    def get_status(self, eventtime): ...
    def get_context(self, cxt=None): ...
    def update_context(self, eventtime) -> None: ...
    def stack_push(self, container) -> None: ...
    def stack_pop(self, update: bool = True): ...
    def stack_size(self): ...
    def stack_peek(self, lvl: int = 0): ...
    def screen_update_event(self, eventtime): ...
    def up(self, fast_rate: bool = False) -> None: ...
    def down(self, fast_rate: bool = False) -> None: ...
    def back(self, force: bool = False, update: bool = True) -> None: ...
    def exit(self, force: bool = False) -> None: ...
    def push_container(self, menu): ...
    def press(self, event: str = 'click') -> None: ...
    def queue_gcode(self, script) -> None: ...
    def dispatch_gcode(self, eventtime) -> None: ...
    def menuitem_from(self, type, **kwargs): ...
    def add_menuitem(self, name, item) -> None: ...
    def lookup_menuitem(self, name, default=...): ...
    def lookup_children(self, ns): ...
    def load_config(self, *args): ...
    def load_menuitems(self, config) -> None: ...
    def key_event(self, key, eventtime) -> None: ...
    @classmethod
    def stripliterals(cls, s): ...
    @classmethod
    def aslatin(cls, s): ...
    @classmethod
    def asflat(cls, s): ...
