from _typeshed import Incomplete

from reactor import Reactor, ReactorTimer
from serialhdl import SerialReader

RTT_AGE: float
DECAY: float
TRANSMIT_EXTRA: float

class ClockSync:
    reactor: Reactor
    serial: SerialReader | None
    get_clock_timer: ReactorTimer
    get_clock_cmd: Incomplete
    queries_pending: int
    mcu_freq: float
    last_clock: int
    clock_est: tuple[float, int, float]
    min_half_rtt: float
    min_rtt_time: float
    time_avg: float
    clock_avg: float
    prediction_variance: float
    last_prediction_time: float
    def __init__(self, reactor: Reactor) -> None: ...
    cmd_queue: Incomplete
    def connect(self, serial: SerialReader) -> None: ...
    def connect_file(self, serial: SerialReader, pace: bool = False) -> None: ...
    def print_time_to_clock(self, print_time: float) -> int: ...
    def clock_to_print_time(self, clock: int) -> float: ...
    def get_clock(self, eventtime: float) -> int: ...
    def estimate_clock_systime(self, reqclock: int) -> float: ...
    def estimated_print_time(self, eventtime: float) -> float: ...
    def clock32_to_clock64(self, clock32: int) -> int: ...
    def is_active(self) -> bool: ...
    def dump_debug(self) -> str: ...
    def stats(self, eventtime: float) -> str: ...
    def calibrate_clock(self, print_time: float, eventtime: float) -> tuple[float, float]: ...

class SecondarySync(ClockSync):
    main_sync: ClockSync
    clock_adj: tuple[float, float]
    last_sync_time: float
    def __init__(self, reactor: Reactor, main_sync: ClockSync) -> None: ...
    def connect(self, serial: SerialReader) -> None: ...
    def connect_file(self, serial: SerialReader, pace: bool = False) -> None: ...
    def print_time_to_clock(self, print_time: float) -> int: ...
    def clock_to_print_time(self, clock: int) -> float: ...
    def dump_debug(self) -> str: ...
    def stats(self, eventtime: float) -> str: ...
    def calibrate_clock(self, print_time: float, eventtime: float) -> tuple[float, float]: ...
