from _typeshed import Incomplete

help_txt: str
re_eval: Incomplete

class KeyboardReader:
    serialport: Incomplete
    baud: Incomplete
    canbus_iface: Incomplete
    canbus_nodeid: Incomplete
    ser: Incomplete
    reactor: Incomplete
    start_time: Incomplete
    clocksync: Incomplete
    fd: Incomplete
    mcu_freq: int
    data: str
    local_commands: Incomplete
    eval_globals: Incomplete
    def __init__(self, reactor, serialport, baud, canbus_iface, canbus_nodeid) -> None: ...
    def connect(self, eventtime): ...
    def output(self, msg) -> None: ...
    def handle_default(self, params) -> None: ...
    def handle_output(self, params) -> None: ...
    def handle_suppress(self, params) -> None: ...
    def update_evals(self, eventtime) -> None: ...
    def command_SET(self, parts) -> None: ...
    def command_DUMP(self, parts, filename=None) -> None: ...
    def command_FILEDUMP(self, parts) -> None: ...
    def command_DELAY(self, parts) -> None: ...
    def command_FLOOD(self, parts) -> None: ...
    def command_SUPPRESS(self, parts) -> None: ...
    def command_STATS(self, parts) -> None: ...
    def command_LIST(self, parts) -> None: ...
    def command_HELP(self, parts) -> None: ...
    def translate(self, line, eventtime): ...
    def process_kbd(self, eventtime) -> None: ...

def main() -> None: ...
