from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any, TypeVar, overload

import configfile
import gcode
from configfile import sentinel as config_sentinel
from reactor import Reactor

message_ready: str
message_startup: str
message_restart: str

_T = TypeVar("_T")

class Printer:
    config_error: type[configfile.error]
    command_error: type[gcode.CommandError]
    bglogger: Incomplete
    start_args: dict[str, Any]
    reactor: Reactor
    state_message: str
    in_shutdown_state: bool
    run_result: str | None
    event_handlers: dict[str, list[Callable[..., Any]]]
    objects: dict[str, Any]
    def __init__(self, main_reactor: Reactor, bglogger, start_args: dict[str, Any]) -> None: ...
    def get_start_args(self) -> dict[str, Any]: ...
    def get_reactor(self) -> Reactor: ...
    def get_state_message(self) -> tuple[str, str]: ...
    def is_shutdown(self) -> bool: ...
    def update_error_msg(self, oldmsg: str, newmsg: str) -> None: ...
    def add_object(self, name: str, obj: Any) -> None: ...
    @overload
    def lookup_object(self, name: str, default: type[config_sentinel] = ...) -> Any: ...
    @overload
    def lookup_object(self, name: str, default: _T) -> Any | _T: ...
    def lookup_objects(self, module: str | None = None) -> list[tuple[str, Any]]: ...
    @overload
    def load_object(self, config: configfile.ConfigWrapper, section: str, default: type[config_sentinel] = ...) -> Any: ...
    @overload
    def load_object(self, config: configfile.ConfigWrapper, section: str, default: _T) -> Any | _T: ...
    def run(self) -> None: ...
    def set_rollover_info(self, name: str, info: str, log: bool = True) -> None: ...
    def invoke_shutdown(self, msg: str, details: dict[str, Any] = {}) -> None: ...
    def invoke_async_shutdown(self, msg: str, details: dict[str, Any] = {}) -> None: ...
    def register_event_handler(self, event: str, callback: Callable[..., Any]) -> None: ...
    def send_event(self, event: str, *params: Any) -> list[Any]: ...
    def request_exit(self, result: str) -> None: ...

def import_test() -> None: ...
def arg_dictionary(option: str, opt_str: str, value: str, parser) -> None: ...
def main() -> None: ...
