from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any, Literal, overload

import configfile
from clocksync import ClockSync
from pins import PinParams
from reactor import ReactorCompletion
from serialhdl import SerialReader
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from klippy import Printer

class error(Exception): ...

MIN_SCHEDULE_TIME: float
MAX_SCHEDULE_TICKS: int
MAX_NOMINAL_DURATION: float

class DummyResponse:
    def __init__(self, serial, name: str, oid: int | None = None) -> None: ...
    def get_response(
        self, cmds, cmd_queue, minclock: int = 0, reqclock: int = 0, retry: bool = True
    ) -> dict[str, Any]: ...

class RetryAsyncCommand:
    TIMEOUT_TIME: float
    RETRY_TIME: float
    serial: SerialReader
    name: str
    oid: int | None
    reactor: Incomplete
    completion: ReactorCompletion
    min_query_time: float
    need_response: bool
    def __init__(self, serial, name: str, oid: int | None = None) -> None: ...
    def handle_callback(self, params: dict[str, Any]) -> None: ...
    def get_response(
        self, cmds, cmd_queue, minclock: int = 0, reqclock: int = 0, retry: bool = True
    ) -> dict[str, Any]: ...

class CommandQueryWrapper:
    def __init__(
        self,
        conn_helper,
        msgformat: str,
        respformat: str,
        oid: int | None = None,
        cmd_queue=None,
        is_async: bool = False,
    ) -> None: ...
    def send(
        self,
        data: tuple[Any, ...] = (),
        minclock: int = 0,
        reqclock: int = 0,
        retry: bool = True,
    ) -> dict[str, Any]: ...
    def send_with_preface(
        self,
        preface_cmd,
        preface_data: tuple[Any, ...] = (),
        data: tuple[Any, ...] = (),
        minclock: int = 0,
        reqclock: int = 0,
        retry: bool = True,
    ) -> dict[str, Any]: ...

class CommandWrapper:
    def __init__(self, conn_helper, msgformat: str, cmd_queue=None) -> None: ...
    def send(
        self, data: tuple[Any, ...] = (), minclock: int = 0, reqclock: int = 0
    ) -> None: ...
    def send_wait_ack(
        self, data: tuple[Any, ...] = (), minclock: int = 0, reqclock: int = 0
    ) -> None: ...
    def get_command_tag(self) -> int: ...

class AsyncResponseWrapper:
    def __init__(
        self,
        conn_helper,
        cfg_helper,
        callback: Callable[[dict[str, Any]], None],
        msgformat: str,
        oid: int | None = None,
    ) -> None: ...
    def unregister(self) -> None: ...

class MCU_trsync:
    REASON_ENDSTOP_HIT: int
    REASON_HOST_REQUEST: int
    REASON_PAST_END_TIME: int
    REASON_COMMS_TIMEOUT: int
    def __init__(self, mcu: MCU, trdispatch) -> None: ...
    def get_mcu(self) -> MCU: ...
    def get_oid(self) -> int: ...
    def get_command_queue(self) -> Incomplete: ...
    def add_stepper(self, stepper) -> None: ...
    def get_steppers(self) -> list[Any]: ...
    def start(
        self,
        print_time: float,
        report_offset: float,
        trigger_completion,
        expire_timeout: float,
    ) -> None: ...
    def set_home_end_time(self, home_end_time: float) -> None: ...
    def stop(self) -> int: ...

TRSYNC_TIMEOUT: float
TRSYNC_SINGLE_MCU_TIMEOUT: float

class TriggerDispatch:
    def __init__(self, mcu: MCU) -> None: ...
    def get_oid(self) -> int: ...
    def get_command_queue(self) -> Incomplete: ...
    def add_stepper(self, stepper) -> None: ...
    def get_steppers(self) -> list[Any]: ...
    def start(self, print_time: float) -> ReactorCompletion: ...
    def wait_end(self, end_time: float) -> None: ...
    def stop(self) -> int: ...

class MCU_endstop:
    def __init__(self, mcu: MCU, pin_params: PinParams) -> None: ...
    def get_mcu(self) -> MCU: ...
    def add_stepper(self, stepper) -> None: ...
    def get_steppers(self) -> list[Any]: ...
    def home_start(
        self,
        print_time: float,
        sample_time: float,
        sample_count: int,
        rest_time: float,
        triggered: bool = True,
    ) -> ReactorCompletion: ...
    def home_wait(self, home_end_time: float) -> float: ...
    def query_endstop(self, print_time: float) -> int: ...

class MCU_digital_out:
    def __init__(self, mcu: MCU, pin_params: PinParams) -> None: ...
    def get_mcu(self) -> MCU: ...
    def setup_max_duration(self, max_duration: float) -> None: ...
    def setup_start_value(self, start_value: int, shutdown_value: int) -> None: ...
    def set_digital(self, print_time: float, value: int) -> None: ...

class MCU_pwm:
    def __init__(self, mcu: MCU, pin_params: PinParams) -> None: ...
    def get_mcu(self) -> MCU: ...
    def setup_max_duration(self, max_duration: float) -> None: ...
    def setup_cycle_time(
        self, cycle_time: float, hardware_pwm: bool = False
    ) -> None: ...
    def setup_start_value(self, start_value: float, shutdown_value: float) -> None: ...
    def next_aligned_print_time(
        self, print_time: float, allow_early: float = 0.0
    ) -> float: ...
    def set_pwm(self, print_time: float, value: float) -> None: ...

class MCU_adc:
    def __init__(self, mcu: MCU, pin_params: PinParams) -> None: ...
    def get_mcu(self) -> MCU: ...
    def setup_adc_sample(
        self,
        report_time: float,
        sample_time: float = 0.0,
        sample_count: int = 1,
        batch_num: int = 1,
        minval: float = 0.0,
        maxval: float = 1.0,
        range_check_count: int = 0,
    ) -> None: ...
    def setup_adc_callback(self, callback: Callable[[float, float], None]) -> None: ...
    def get_last_value(self) -> tuple[float, float]: ...

class MCURestartHelper:
    def __init__(self, config: configfile.ConfigWrapper, conn_helper) -> None: ...
    def check_restart_on_crc_mismatch(self) -> None: ...
    def check_restart_on_send_config(self) -> None: ...
    def check_restart_on_attach(self) -> None: ...
    def lookup_attach_uart_rts(self) -> Incomplete: ...

class MCUConnectHelper:
    def __init__(
        self, config: configfile.ConfigWrapper, mcu: MCU, clocksync: ClockSync
    ) -> None: ...
    def get_mcu(self) -> MCU: ...
    def get_serial(self) -> SerialReader: ...
    def get_clocksync(self) -> ClockSync: ...
    def get_serialport(self) -> str: ...
    def get_restart_helper(self) -> MCURestartHelper: ...
    def log_info(self) -> None: ...
    def force_local_shutdown(self) -> None: ...
    def check_timeout(self, eventtime: float) -> None: ...
    def is_shutdown(self) -> bool: ...
    def get_shutdown_msg(self) -> tuple[str, str]: ...

class MCUStatsHelper:
    def __init__(
        self, config: configfile.ConfigWrapper, conn_helper: MCUConnectHelper
    ) -> None: ...
    def get_status(self, eventtime: float | None = None) -> dict[str, Any]: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...

class MCUConfigHelper:
    def __init__(
        self, config: configfile.ConfigWrapper, conn_helper: MCUConnectHelper
    ) -> None: ...
    def is_config_finalized(self) -> bool: ...
    @overload
    def setup_pin(
        self, pin_type: Literal["endstop"], pin_params: PinParams
    ) -> MCU_endstop: ...
    @overload
    def setup_pin(
        self, pin_type: Literal["digital_out"], pin_params: PinParams
    ) -> MCU_digital_out: ...
    @overload
    def setup_pin(self, pin_type: Literal["pwm"], pin_params: PinParams) -> MCU_pwm: ...
    @overload
    def setup_pin(self, pin_type: Literal["adc"], pin_params: PinParams) -> MCU_adc: ...
    def create_oid(self) -> int: ...
    def register_config_callback(self, cb: Callable[[], None]) -> None: ...
    def add_config_cmd(
        self, cmd: str, is_init: bool = False, on_restart: bool = False
    ) -> None: ...
    def register_post_init_callback(self, cb: Callable[[], None]) -> None: ...
    def get_query_slot(self, oid: int) -> int: ...
    def seconds_to_clock(self, time: float) -> int: ...
    def request_move_queue_slot(self) -> None: ...

class MCU:
    error = error
    def __init__(
        self, config: configfile.ConfigWrapper, clocksync: ClockSync
    ) -> None: ...
    def get_name(self) -> str: ...
    def get_printer(self) -> Printer: ...
    def is_fileoutput(self) -> bool: ...
    @overload
    def setup_pin(
        self, pin_type: Literal["endstop"], pin_params: PinParams
    ) -> MCU_endstop: ...
    @overload
    def setup_pin(
        self, pin_type: Literal["digital_out"], pin_params: PinParams
    ) -> MCU_digital_out: ...
    @overload
    def setup_pin(self, pin_type: Literal["pwm"], pin_params: PinParams) -> MCU_pwm: ...
    @overload
    def setup_pin(self, pin_type: Literal["adc"], pin_params: PinParams) -> MCU_adc: ...
    def create_oid(self) -> int: ...
    def register_config_callback(self, cb: Callable[[], None]) -> None: ...
    def add_config_cmd(
        self, cmd: str, is_init: bool = False, on_restart: bool = False
    ) -> None: ...
    def request_move_queue_slot(self) -> None: ...
    def get_query_slot(self, oid: int) -> int: ...
    def seconds_to_clock(self, time: float) -> int: ...
    def min_schedule_time(self) -> float: ...
    def max_nominal_duration(self) -> float: ...
    def lookup_command(self, msgformat: str, cq=None) -> CommandWrapper: ...
    def lookup_query_command(
        self,
        msgformat: str,
        respformat: str,
        oid: int | None = None,
        cq=None,
        is_async: bool = False,
    ) -> CommandQueryWrapper: ...
    def try_lookup_command(self, msgformat: str) -> CommandWrapper | None: ...
    def alloc_command_queue(self) -> Incomplete: ...
    def register_serial_response(
        self, cb: Callable[[dict[str, Any]], None], msg: str, oid: int | None = None
    ) -> AsyncResponseWrapper: ...
    def check_valid_response(self, msgformat: str) -> None: ...
    def get_enumerations(self) -> dict[str, dict[int, str]]: ...
    def get_constants(self) -> dict[str, Any]: ...
    def get_constant_float(self, name: str) -> float: ...
    def print_time_to_clock(self, print_time: float) -> int: ...
    def clock_to_print_time(self, clock: int) -> float: ...
    def estimated_print_time(self, eventtime: float) -> float: ...
    def clock32_to_clock64(self, clock32: int) -> int: ...
    def calibrate_clock(
        self, print_time: float, eventtime: float
    ) -> tuple[float, float]: ...
    def get_status(self, eventtime: float | None = None) -> dict[str, Any]: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...

def add_printer_objects(config: configfile.ConfigWrapper) -> None: ...
def get_printer_mcu(printer: Printer, name: str) -> MCU: ...
