import logging
import logging.handlers
from _typeshed import Incomplete

class QueueHandler(logging.Handler):
    queue: Incomplete
    def __init__(self, queue) -> None: ...
    def emit(self, record) -> None: ...

class QueueListener(logging.handlers.TimedRotatingFileHandler):
    bg_queue: Incomplete
    bg_thread: Incomplete
    rollover_info: Incomplete
    def __init__(self, filename) -> None: ...
    def stop(self) -> None: ...
    def set_rollover_info(self, name, info) -> None: ...
    def clear_rollover_info(self) -> None: ...
    def doRollover(self) -> None: ...

MainQueueHandler: Incomplete

def setup_bg_logging(filename, debuglevel): ...
def clear_bg_logging() -> None: ...
