import greenlet
from collections.abc import Callable
from typing import Any, TypeVar

class ReactorError(Exception): ...

_T = TypeVar("_T")

class ReactorTimer:
    callback: Callable[[float], float]
    waketime: float
    timer_is_running: bool
    def __init__(self, callback: Callable[[float], float], waketime: float) -> None: ...

class ReactorCompletion:
    class sentinel: ...
    reactor: SelectReactor
    result: Any
    waiting: list[ReactorGreenlet]
    def __init__(self, reactor: SelectReactor) -> None: ...
    def test(self) -> bool: ...
    def complete(self, result: Any) -> None: ...
    def wait(self, waketime: float = ..., waketime_result: Any = None) -> Any: ...

class ReactorCallback:
    reactor: SelectReactor
    timer: ReactorTimer
    callback: Callable[[float], Any]
    completion: ReactorCompletion
    def __init__(
        self, reactor: SelectReactor, callback: Callable[[float], Any], waketime: float
    ) -> None: ...
    def invoke(self, eventtime: float) -> float: ...

class ReactorFileHandler:
    fd: int
    read_callback: Callable[[float], None]
    write_callback: Callable[[float], None] | None
    def __init__(
        self,
        fd: int,
        read_callback: Callable[[float], None],
        write_callback: Callable[[float], None] | None = None,
    ) -> None: ...

class ReactorGreenlet(greenlet.greenlet):
    timer: ReactorTimer | None
    def __init__(self, run: Callable[[], Any]) -> None: ...

class ReactorMutex:
    reactor: SelectReactor
    is_locked: bool
    next_pending: bool
    queue: list[ReactorGreenlet]
    lock: Callable[[], None]
    unlock: Callable[..., None]
    def __init__(self, reactor: SelectReactor, is_locked: bool) -> None: ...
    def test(self) -> bool: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        type: type[BaseException] | None = None,
        value: BaseException | None = None,
        tb: Any = None,
    ) -> None: ...

class ReactorPreventPause:
    reactor: SelectReactor
    def __init__(self, reactor: SelectReactor) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        type: type[BaseException] | None = None,
        value: BaseException | None = None,
        tb: Any = None,
    ) -> None: ...

class SelectReactor:
    NOW: float
    NEVER: float
    monotonic: Callable[[], float]
    def __init__(self, gc_checking: bool = False) -> None: ...
    def get_gc_stats(self) -> dict[str, Any]: ...
    def update_timer(self, timer_handler: ReactorTimer, waketime: float) -> None: ...
    def register_timer(
        self, callback: Callable[[float], float], waketime: float = ...
    ) -> ReactorTimer: ...
    def unregister_timer(self, timer_handler: ReactorTimer) -> None: ...
    def completion(self) -> ReactorCompletion: ...
    def register_callback(
        self, callback: Callable[[float], Any], waketime: float = ...
    ) -> ReactorCompletion: ...
    def register_async_callback(
        self, callback: Callable[[], Any], waketime: float = ...
    ) -> None: ...
    def async_complete(self, completion: ReactorCompletion, result: Any) -> None: ...
    def pause(self, waketime: float) -> float: ...
    def assert_no_pause(self) -> ReactorPreventPause: ...
    def verify_can_pause(self) -> None: ...
    def mutex(self, is_locked: bool = False) -> ReactorMutex: ...
    def register_fd(
        self,
        fd: int,
        read_callback: Callable[[float], None],
        write_callback: Callable[[float], None] | None = None,
    ) -> ReactorFileHandler: ...
    def unregister_fd(self, file_handler: ReactorFileHandler) -> None: ...
    def set_fd_wake(
        self,
        file_handler: ReactorFileHandler,
        is_readable: bool = True,
        is_writeable: bool = False,
    ) -> None: ...
    def run(self) -> None: ...
    def end(self) -> None: ...
    def finalize(self) -> None: ...

class PollReactor(SelectReactor):
    def __init__(self, gc_checking: bool = False) -> None: ...
    def register_fd(
        self,
        fd: int,
        read_callback: Callable[[float], None],
        write_callback: Callable[[float], None] | None = None,
    ) -> ReactorFileHandler: ...
    def unregister_fd(self, file_handler: ReactorFileHandler) -> None: ...
    def set_fd_wake(
        self,
        file_handler: ReactorFileHandler,
        is_readable: bool = True,
        is_writeable: bool = False,
    ) -> None: ...

class EPollReactor(SelectReactor):
    def __init__(self, gc_checking: bool = False) -> None: ...
    def register_fd(
        self,
        fd: int,
        read_callback: Callable[[float], None],
        write_callback: Callable[[float], None] | None = None,
    ) -> ReactorFileHandler: ...
    def unregister_fd(self, file_handler: ReactorFileHandler) -> None: ...
    def set_fd_wake(
        self,
        file_handler: ReactorFileHandler,
        is_readable: bool = True,
        is_writeable: bool = False,
    ) -> None: ...

# pony: runtime falls back to SelectReactor when select.poll is unavailable
Reactor = PollReactor
