from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any

from msgproto import MessageParser
from reactor import Reactor

class error(Exception): ...

class SerialReader:
    reactor: Reactor
    warn_prefix: str
    mcu_name: str
    sq_name: str
    serial_dev: Incomplete
    msgparser: MessageParser
    serialqueue: Incomplete
    default_cmd_queue: Incomplete
    stats_buf: Incomplete
    lock: Incomplete
    background_thread: Incomplete
    handlers: dict[tuple[str, int | None], Callable[[dict[str, Any]], None]]
    last_notify_id: int
    pending_notifications: dict[int, Incomplete]
    def __init__(self, reactor: Reactor, mcu_name: str = '') -> None: ...
    def connect_canbus(self, canbus_uuid: int, canbus_nodeid: int, canbus_iface: str = 'can0') -> None: ...
    def connect_pipe(self, filename: str) -> None: ...
    def connect_uart(self, serialport: str, baud: int, rts: bool = True) -> None: ...
    def connect_file(self, debugoutput, dictionary: bytes, pace: bool = False) -> None: ...
    def set_clock_est(self, freq: float, conv_time: float, conv_clock: int, last_clock: int) -> None: ...
    def disconnect(self) -> None: ...
    def stats(self, eventtime: float) -> str: ...
    def get_reactor(self) -> Reactor: ...
    def get_msgparser(self) -> MessageParser: ...
    def get_serialqueue(self) -> Incomplete: ...
    def get_default_command_queue(self) -> Incomplete: ...
    def register_response(self, callback: Callable[[dict[str, Any]], None], name: str, oid: int | None = None) -> None: ...
    def raw_send(self, cmd: bytes, minclock: int, reqclock: int, cmd_queue) -> None: ...
    def raw_send_wait_ack(self, cmd: bytes, minclock: int, reqclock: int, cmd_queue) -> None: ...
    def send(self, msg: str, minclock: int = 0, reqclock: int = 0) -> None: ...
    def send_with_response(self, msg: str, response: str) -> dict[str, Any]: ...
    def alloc_command_queue(self) -> Incomplete: ...
    def dump_debug(self) -> str: ...
    def handle_unknown(self, params: dict[str, Any]) -> None: ...
    def handle_output(self, params: dict[str, Any]) -> None: ...
    def handle_default(self, params: dict[str, Any]) -> None: ...

class SerialRetryCommand:
    serial: SerialReader
    name: str
    oid: int | None
    last_params: dict[str, Any] | None
    def __init__(self, serial: SerialReader, name: str, oid: int | None = None) -> None: ...
    def handle_callback(self, params: dict[str, Any]) -> None: ...
    def get_response(self, cmds, cmd_queue, minclock: int = 0, reqclock: int = 0, retry: bool = True) -> dict[str, Any]: ...

def stk500v2_leave(ser, reactor: Reactor) -> None: ...
def cheetah_reset(serialport: str, reactor: Reactor) -> None: ...
def arduino_reset(serialport: str, reactor: Reactor) -> None: ...
