from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any, NamedTuple

import configfile
from mcu import MCU, MCU_endstop
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from klippy.klippy import Printer

class error(Exception): ...

MIN_BOTH_EDGE_DURATION: float
MIN_OPTIMIZED_BOTH_EDGE_DURATION: float
MAX_STEPCOMPRESS_ERROR: float

class HomingInfo(NamedTuple):
    speed: float
    position_endstop: float
    retract_speed: float
    retract_dist: float
    positive_dir: bool
    second_homing_speed: float

class MCU_stepper:
    def __init__(
        self,
        config: configfile.ConfigWrapper,
        step_pin_params,
        dir_pin_params,
        rotation_dist: float,
        steps_per_rotation: float,
        step_pulse_duration: float | None = None,
        units_in_radians: bool = False,
    ) -> None: ...
    def get_mcu(self) -> MCU: ...
    def get_name(self, short: bool = False) -> str: ...
    def units_in_radians(self) -> bool: ...
    def get_pulse_duration(self) -> tuple[float, bool]: ...
    def setup_default_pulse_duration(
        self, pulse_duration: float, step_both_edge: bool
    ) -> None: ...
    def setup_itersolve(self, alloc_func: Callable[..., Any], *params: Any) -> None: ...
    def get_oid(self) -> int: ...
    def get_step_dist(self) -> float: ...
    def get_rotation_distance(self) -> tuple[float, float]: ...
    def set_rotation_distance(self, rotation_dist: float) -> None: ...
    def get_dir_inverted(self) -> tuple[bool, bool]: ...
    def set_dir_inverted(self, invert_dir: bool) -> None: ...
    def calc_position_from_coord(self, coord: list[float]) -> float: ...
    def set_position(self, coord: list[float]) -> None: ...
    def get_commanded_position(self) -> float: ...
    def get_mcu_position(self, cmd_pos: float | None = None) -> int: ...
    def get_past_mcu_position(self, print_time: float) -> int: ...
    def mcu_to_commanded_position(self, mcu_pos: int) -> float: ...
    def dump_steps(
        self, count: int, start_clock: int, end_clock: int
    ) -> list[tuple[int, int, int]]: ...
    def get_stepper_kinematics(self) -> Incomplete: ...
    def set_stepper_kinematics(self, sk) -> Incomplete: ...
    def note_homing_end(self) -> None: ...
    def get_trapq(self) -> Incomplete: ...
    def set_trapq(self, tq) -> None: ...
    def add_active_callback(self, cb: Callable[[], None]) -> None: ...
    def is_active_axis(self, axis: str) -> bool: ...

def PrinterStepper(
    config: configfile.ConfigWrapper, units_in_radians: bool = False
) -> MCU_stepper: ...
def parse_gear_ratio(
    config: configfile.ConfigWrapper, note_valid: bool
) -> tuple[float, float]: ...
def parse_step_distance(
    config: configfile.ConfigWrapper,
    units_in_radians: bool | None = None,
    note_valid: bool = False,
) -> float: ...

class GenericPrinterRail:
    stepper_units_in_radians: bool
    printer: Printer
    name: str
    steppers: list[MCU_stepper]
    endstops: list[tuple[MCU_endstop, str]]
    endstop_map: dict[str, MCU_endstop]
    endstop_pin: str
    query_endstops: Incomplete
    position_endstop: float
    position_min: float
    position_max: float
    homing_speed: float
    second_homing_speed: float
    homing_retract_speed: float
    homing_retract_dist: float
    homing_positive_dir: bool
    def __init__(
        self,
        config: configfile.ConfigWrapper,
        need_position_minmax: bool = True,
        default_position_endstop: float | None = None,
        units_in_radians: bool = False,
    ) -> None: ...
    def get_name(self, short: bool = False) -> str: ...
    def get_range(self) -> tuple[float, float]: ...
    def get_homing_info(self) -> HomingInfo: ...
    def get_steppers(self) -> list[MCU_stepper]: ...
    def get_endstops(self) -> list[tuple[MCU_endstop, str]]: ...
    def lookup_endstop(self, endstop_pin: str, name: str) -> MCU_endstop: ...
    get_commanded_position: Callable[[], float]
    calc_position_from_coord: Callable[[list[float]], float]
    def add_stepper(
        self,
        stepper: MCU_stepper,
        endstop_pin: str | None = None,
        endstop_name: str | None = None,
    ) -> None: ...
    def add_stepper_from_config(self, config: configfile.ConfigWrapper) -> None: ...
    def setup_itersolve(self, alloc_func: Callable[..., Any], *params: Any) -> None: ...
    def set_trapq(self, trapq) -> None: ...
    def set_position(self, coord: list[float]) -> None: ...

def LookupRail(
    config: configfile.ConfigWrapper,
    need_position_minmax: bool = True,
    default_position_endstop: float | None = None,
    units_in_radians: bool = False,
) -> GenericPrinterRail: ...
def LookupMultiRail(
    config: configfile.ConfigWrapper,
    need_position_minmax: bool = True,
    default_position_endstop: float | None = None,
    units_in_radians: bool = False,
) -> list[GenericPrinterRail]: ...
