from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any

import configfile
import gcode
import klippy
from mcu import MCU
from reactor import Reactor, ReactorCompletion, ReactorTimer

class Move:
    toolhead: ToolHead
    start_pos: list[float]
    end_pos: list[float]
    accel: float
    junction_deviation: float
    timing_callbacks: list[Callable[[float], None]]
    is_kinematic_move: bool
    axes_d: list[float]
    move_d: float
    axes_r: list[float]
    min_move_t: float
    max_start_v2: float
    max_cruise_v2: float
    delta_v2: float
    next_junction_v2: float
    max_mcr_start_v2: float
    mcr_delta_v2: float
    def __init__(self, toolhead: ToolHead, start_pos: list[float], end_pos: list[float], speed: float) -> None: ...
    def limit_speed(self, speed: float, accel: float) -> None: ...
    def limit_next_junction_speed(self, speed: float) -> None: ...
    def move_error(self, msg: str = 'Move out of range') -> None: ...
    def calc_junction(self, prev_move: Move) -> None: ...
    start_v: float
    cruise_v: float
    end_v: float
    accel_t: float
    cruise_t: float
    decel_t: float
    def set_junction(self, start_v2: float, cruise_v2: float, end_v2: float) -> None: ...

LOOKAHEAD_FLUSH_TIME: float

class LookAheadQueue:
    queue: list[Move]
    junction_flush: float
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def set_flush_time(self, flush_time: float) -> None: ...
    def is_empty(self) -> bool: ...
    def get_last(self) -> Move | None: ...
    def flush(self, lazy: bool = False) -> list[Move]: ...
    def add_move(self, move: Move) -> None: ...

BUFFER_TIME_HIGH: float
BUFFER_TIME_START: float
PRIMING_CMD_TIME: float

class ToolHead:
    printer: klippy.Printer
    reactor: Reactor
    mcu: MCU
    lookahead: LookAheadQueue
    commanded_pos: list[float]
    max_velocity: float
    max_accel: float
    min_cruise_ratio: float
    square_corner_velocity: float
    junction_deviation: float
    check_stall_time: float
    print_stall: int
    can_pause: bool
    need_check_pause: float
    print_time: float
    special_queuing_state: str
    priming_timer: ReactorTimer | None
    motion_queuing: Incomplete
    trapq: Incomplete
    trapq_append: Incomplete
    Coord: type[gcode.Coord]
    extra_axes: list[Any]
    extra_axes_status: dict[str, Any]
    kin: Any
    def __init__(self, config: configfile.ConfigWrapper) -> None: ...
    def flush_step_generation(self) -> None: ...
    def get_last_move_time(self) -> float: ...
    def get_position(self) -> list[float]: ...
    def set_position(self, newpos: list[float], homing_axes: str = '') -> None: ...
    def limit_next_junction_speed(self, speed: float) -> None: ...
    def move(self, newpos: list[float], speed: float) -> None: ...
    def manual_move(self, coord: list[float], speed: float) -> None: ...
    def dwell(self, delay: float) -> None: ...
    def wait_moves(self) -> None: ...
    def set_extruder(self, extruder: Any, extrude_pos: float) -> None: ...
    def get_extruder(self) -> Any: ...
    def add_extra_axis(self, ea: Any, axis_pos: float) -> None: ...
    def remove_extra_axis(self, ea: Any) -> None: ...
    def get_extra_axes(self) -> list[Any]: ...
    def drip_move(self, newpos: list[float], speed: float, drip_completion: ReactorCompletion) -> None: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...
    def check_busy(self, eventtime: float) -> tuple[float, float, bool]: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...
    def get_kinematics(self) -> Any: ...
    def get_trapq(self) -> Incomplete: ...
    def register_lookahead_callback(self, callback: Callable[[float], None]) -> None: ...
    def get_max_velocity(self) -> tuple[float, float]: ...
    def set_max_velocities(self, max_velocity: float | None, max_accel: float | None, square_corner_velocity: float | None, min_cruise_ratio: float | None) -> None: ...

class ToolHeadCommandHelper:
    printer: klippy.Printer
    toolhead: ToolHead
    def __init__(self, config: configfile.ConfigWrapper) -> None: ...
    def cmd_G4(self, gcmd: gcode.GCodeCommand) -> None: ...
    def cmd_M400(self, gcmd: gcode.GCodeCommand) -> None: ...
    cmd_SET_VELOCITY_LIMIT_help: str
    def cmd_SET_VELOCITY_LIMIT(self, gcmd: gcode.GCodeCommand) -> None: ...
    def cmd_M204(self, gcmd: gcode.GCodeCommand) -> None: ...

def add_printer_objects(config: configfile.ConfigWrapper) -> None: ...
