from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any, TypeVar, overload

import gcode
from reactor import Reactor
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from klippy.klippy import Printer

json_loads_byteify: Callable[[dict[str, Any]], dict[str, Any]]

def json_dumps(obj: Any) -> bytes: ...
def json_loads(data: bytes | str) -> Any: ...

REQUEST_LOG_SIZE: int

class WebRequestError(gcode.CommandError):
    def __init__(self, message: str) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class Sentinel: ...

_T = TypeVar("_T")

class WebRequest:
    error = WebRequestError
    client_conn: ClientConnection
    id: int | None
    method: str | None
    params: dict[str, Any]
    response: dict[str, Any] | None
    is_error: bool
    def __init__(self, client_conn: ClientConnection, request: bytes | str) -> None: ...
    def get_client_connection(self) -> ClientConnection: ...
    @overload
    def get(
        self,
        item: str,
        default: type[Sentinel] = ...,
        types: tuple[type, ...] | None = None,
    ) -> Any: ...
    @overload
    def get(
        self, item: str, default: _T, types: tuple[type, ...] | None = None
    ) -> Any | _T: ...
    @overload
    def get_str(self, item: str, default: type[Sentinel] = ...) -> str: ...
    @overload
    def get_str(self, item: str, default: _T) -> str | _T: ...
    @overload
    def get_int(self, item: str, default: type[Sentinel] = ...) -> int: ...
    @overload
    def get_int(self, item: str, default: _T) -> int | _T: ...
    @overload
    def get_float(self, item: str, default: type[Sentinel] = ...) -> float: ...
    @overload
    def get_float(self, item: str, default: _T) -> float | _T: ...
    @overload
    def get_dict(self, item: str, default: type[Sentinel] = ...) -> dict[str, Any]: ...
    @overload
    def get_dict(self, item: str, default: _T) -> dict[str, Any] | _T: ...
    def get_method(self) -> str | None: ...
    def set_error(self, error: WebRequestError) -> None: ...
    def send(self, data: dict[str, Any]) -> None: ...
    def finish(self) -> None: ...

class ServerSocket:
    printer: Printer
    webhooks: WebHooks
    reactor: Reactor
    sock: Incomplete
    clients: dict[int, ClientConnection]
    fd_handle: Incomplete
    def __init__(self, webhooks: WebHooks, printer: Printer) -> None: ...
    def pop_client(self, client_id: int) -> None: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...

class ClientConnection:
    printer: Printer
    webhooks: WebHooks
    reactor: Reactor
    server: ServerSocket
    uid: int
    sock: Incomplete
    fd_handle: Incomplete
    partial_data: bytes
    is_blocking: bool
    blocking_count: int
    request_log: Incomplete
    def __init__(self, server: ServerSocket, sock) -> None: ...
    def dump_request_log(self) -> None: ...
    def set_client_info(
        self, client_info: str, state_msg: str | None = None
    ) -> None: ...
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def process_received(self, eventtime: float) -> None: ...
    def send(self, data: bytes) -> None: ...

class WebHooks:
    printer: Printer
    sconn: ServerSocket
    def __init__(self, printer: Printer) -> None: ...
    def register_endpoint(
        self, path: str, callback: Callable[[WebRequest], None]
    ) -> None: ...
    def register_mux_endpoint(
        self, path: str, key: str, value: str, callback: Callable[[WebRequest], None]
    ) -> None: ...
    def get_connection(self) -> ServerSocket: ...
    def get_callback(self, path: str) -> Callable[[WebRequest], None] | None: ...
    def get_status(self, eventtime: float) -> dict[str, Any]: ...
    def stats(self, eventtime: float) -> tuple[bool, str]: ...
    def call_remote_method(self, method: str, **kwargs: Any) -> None: ...

class GCodeHelper:
    printer: Printer
    gcode: gcode.GCodeDispatch
    is_output_registered: bool
    clients: list[ClientConnection]
    def __init__(self, printer: Printer) -> None: ...

SUBSCRIPTION_REFRESH_TIME: float

class QueryStatusHelper:
    printer: Printer
    clients: list[ClientConnection]
    pending_queries: Incomplete
    query_timer: Incomplete
    last_query: Incomplete
    def __init__(self, printer: Printer) -> None: ...

def add_early_printer_objects(printer: Printer) -> None: ...
